bip.mediawiki

Remove the acknowledgements section since it's still a draft

---

tests/integration.rs
tests/list.rs

There can be zero-valued inputs and outputs, so add a test for that.

Test null outputs and inputs

---

justfile

Add recipe to serve docs using Python 3 simple http server.

Add serve-docs recipe

---

src/ordinal.rs
src/subcommand/traits.rs

I think these are better names than "cycle number", "epoch index", "period index", and "block offset", mostly because they map cleanly to the degree notation.

Use hour, minute, second, and third terminology

---

docs/index.html

Make the first paragraph of the homepage clearer.

Revise homepage

---

src/index.rs

Seems to have issues at the moment: https://github.com/cberner/redb/issues/337

Don't use redb checksum write strategy

---

static/index.css

- Don't underline by default
- Underline on hover
- Don't change visited link color

Style links

---

static/index.css

- Keep numbers inside of containing div
- Don't wrap

Improve <ol> style

---

templates/clock.svg

Let me know what you think of the text.
When hovering the ring marks change color to the type of ordinal they represent.

added tooltips to clock

---

src/subcommand/server.rs
src/subcommand/server/templates/clock.rs
templates/clock.svg

Add more links and labels to clocks

---

src/subcommand/server.rs
src/test.rs
tests/server.rs

added some methods and RPC endpoints to the test `BitcoinRpcServer` so that we have a mempool and a transaction index

Convert even more unit tests

---

.github/workflows/build-docs.yaml
.github/workflows/ci.yaml
.github/workflows/deploy-docs.yaml
.github/workflows/release.yaml

Workflows are a little easier to manage if the jobs have descriptive names.

Rename workflow jobs

---

docs/content/bounty/0.md
docs/content/bounty/1.md
docs/content/bounty/2.md
docs/content/bounty/_index.md
docs/templates/bounties.html
docs/templates/bounty.html
docs/templates/index.html
docs/templates/section.html
static/index.css
templates/home.html

Add new bounty

---

Cargo.lock
Cargo.toml
test-bitcoincore-rpc/Cargo.toml

- Bump ord to 0.0.5
- Bump test-bitcoincore-rpc to 0.0.1

Release 0.0.5

---

src/index.rs
src/subcommand/server.rs
src/subcommand/server/templates/input.rs
src/subcommand/wallet/transaction_builder.rs
test-bitcoincore-rpc/src/server.rs
test-bitcoincore-rpc/src/state.rs

disable RBF

---

src/index.rs
src/options.rs
src/ordinal.rs
src/subcommand/find.rs
src/subcommand/list.rs
src/subcommand/rune/publish.rs
src/subcommand/server.rs
src/subcommand/wallet.rs
src/subcommand/wallet/send.rs
src/subcommand/wallet/transaction_builder.rs
tests/find.rs
tests/list.rs

Lowercase error messages

---

Cargo.lock
Cargo.toml
src/index.rs

Release 0.0.6

---

CHANGELOG.md
Cargo.lock
Cargo.toml
justfile

- Bump version: 0.0.6 → 0.1.0
- Start keeping a changelog

Release 0.1.0

---

src/index/updater.rs

Abort update if at unexpected height

---

src/index/updater.rs

Calculate txids in background thread

---

src/subcommand/wallet/inscribe.rs
tests/wallet.rs

refuse to inscribe already inscribed utxo

---

src/subcommand/wallet/inscribe.rs
test-bitcoincore-rpc/src/api.rs
test-bitcoincore-rpc/src/lib.rs
test-bitcoincore-rpc/src/server.rs

Save reveal priv key

---

src/subcommand/wallet.rs
src/subcommand/wallet/utxos.rs
tests/wallet.rs

list utxos in wallet

---

src/index/updater.rs
src/subcommand/wallet.rs
src/subcommand/wallet/inscriptions.rs
tests/wallet.rs

allow listing inscriptions in wallet

---

.github/workflows/release.yaml

ARM on Linux runs into errors building ring: https://github.com/briansmith/ring/issues/1414

Build releases for arm

---

src/chain.rs
src/index/updater.rs

Opening this as a draft, since it needs a real height for signet.

Don't request transactions if below first inscription height

---

static/index.css

Style latest inscriptions

---

src/index.rs
src/inscription.rs
src/subcommand/server/templates/content.rs
src/subcommand/server/templates/home.rs
src/subcommand/server/templates/inscription.rs
src/subcommand/server/templates/sat.rs
static/index.css
tests/server.rs
tests/wallet.rs

I think this is worth doing, even if they're a little awkward looking. We want people to know that text inscriptions are possible.

Show text inscriptions on homepage

---

src/templates.rs
templates/page.html

Display alpha on mainnet

---

src/index.rs
src/subcommand/server.rs
src/templates/input.rs
src/templates/output.rs
src/templates/transaction.rs
test-bitcoincore-rpc/src/state.rs

See https://github.com/rust-bitcoin/rust-bitcoin/issues/1517.

Avoid push_scriptint

---

src/subcommand/wallet/send.rs
tests/server.rs
tests/wallet.rs

Swap arguments to ord wallet send

---

src/inscription.rs

Check that additional envelopes and outputs are ignored

---

src/subcommand/wallet/balance.rs
tests/wallet/balance.rs

`balance` only show cardinal output amounts

---

static/index.js
templates/page.html

Don't process nav keys when search box is focused

---

Cargo.lock
Cargo.toml
src/subcommand/server.rs

Compress responses

---

static/index.css

Hide overflowing ordered lists

---

src/templates/home.rs
templates/home.html

This was just kind of bothering me.

Remove of ellipsis after more

---

docs/src/SUMMARY.md

Thanks for making Ordinals. It really caught my attention. Noticed a tiny typo in the sidebar.

Fix typo in docs sidebar

---

Cargo.toml
README.md

Set rustc version in Cargo.toml & README

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/index.rs

- Bump version: 0.4.2 → 0.5.0
- Update database schema version

Release 0.5.0

---

CHANGELOG.md

Fix changelog dates: 2022 → 2023

---

docs/src/overview.md

Fix typos in overview.md

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Release 0.5.1

---

README.md

Added livestream to README.md

---

docs/src/guides/inscriptions.md
src/subcommand/wallet/inscribe.rs
tests/lib.rs
tests/wallet/inscribe.rs

Too many people are inscribing with the default 1 sat/vB fee rate.
This should help.

Mandatory fee rate for inscribe

---

CHANGELOG.md
Cargo.lock
Cargo.toml
justfile
src/index/fetcher.rs

Release 0.5.2

---

docs/src/donate.md

I looked at #2033, but realized I'm just too particular, and wanted to write my own prose.
This attempts to solve the following problems:
- People don't realize that the donation addresses correspond to physical opendimes
- People don't realize that inscriptions can be sent to the donation addresses.

Improve donation page

---

src/index/updater/inscription_updater.rs

This makes it easier to understand the purpose of the origin enum fields.

Use struct variants in Origin enum

---

docs/src/donate.md

Added separate donation address for inscriptions to make managing the wallet easier.
@casey @raphjaph please review and carefully check address.

Update donate.md for inscriptions donations.

---

docs/src/guides/collecting/sparrow-wallet.md

Fix typo in sparrow-wallet.md

---

README.md
justfile

Add contributing section

---

deploy/setup

Vaccuum log with every new deploy

---

src/inscription.rs

Use tapscript extraction from rust-bitcoin

---

Cargo.lock
Cargo.toml

Found with `cargo +nightly udeps`.

Remove unused itertools dependency

---

docs/po/zh.po

updated zh.po with typo and format error

update zh.po with typo and format error

---

static/index.js

Prevents default search which currently routes to `/sat`

Bugfix prevent default search

---

docs/po/ja.po

1,update ja.po "provenance section" ; 
2,fix format error

update ja.po with provenance section

---

src/index.rs
src/inscription.rs
src/subcommand/preview.rs
src/subcommand/server.rs
src/subcommand/wallet/inscribe.rs
templates/inscription.html
tests/decode.rs
tests/wallet/inscribe.rs

Allows inscriptions to declare their protocol in a dedicated field.

Add metaprotocol field

---

bin/package

Packages it similar to how bitcoin release does it, avoids making a tarbomb.

Fixes release tarbomb

---

docs/src/guides/testing.md

Testing.md add regtest flag to bitcoin-cli mine

---

docs/src/guides/inscriptions.md

Update parent-child guide

---

src/envelope.rs
src/index.rs
src/index/updater/inscription_updater.rs
src/inscription.rs
src/subcommand/wallet/inscribe.rs
test-bitcoincore-rpc/src/state.rs

TODO:
~~- [ ] move logic into `update_inscription_location()`~~

Implement pointer spec

---

.github/workflows/ci.yaml
docs/po/fr.po
docs/theme/index.hbs
justfile

Hi @raphjaph, here's the French translation of the Handbook, as per [OMB Bounty 16A](https://github.com/OrdinalMaxiBiz/bounties/issues/18), translated according to the specifications.

Add French version of handbook

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Bump version: 0.9.0 → 0.10.0

Release 0.10.0

---

README.md
docs/po/zh.po

Update README.md and zh.po

---

docs/src/guides/explorer.md

Closes https://github.com/ordinals/ord/issues/2600

Update docs with new position of --enable-json-api

---

src/index.rs

Fix statistics table and increment schema version

---

templates/page.html

Ordicord is a good place to seek help. This should make it easier to discover.

Add a link to Ordicord

---

docs/po/ar.po
docs/po/de.po
docs/po/es.po
docs/po/ja.po
docs/po/pt.po
docs/po/ru.po
docs/po/zh.po
docs/src/guides/inscriptions.md
docs/src/guides/testing.md

update docs to pass --file to `wallet inscribe`

---

docs/src/guides/sat-hunting.md

Clarify sat hunting guide

---

.github/workflows/ci.yaml
docs/po/hi.po
docs/theme/index.hbs
justfile

Hey @raphjaph ! Here is the new pull request for the hindi translation of the ordinals handbook. This is the same .po file from which i have successfully generated an mdbook. This is for OMB Bounty https://github.com/OrdinalMaxiBiz/bounties/issues/19
Thanks again!

Hindi Translation of Handbook V2

---

src/index/updater.rs

This helper function isn't doing much, and figuring out what it does requires going to a function definition, so I inlined it.

Remove index_block_inscription_numbers helper function

---

static/index.css

Don't color links in headers

---

src/subcommand/server.rs

Move rune tests above other tests

---

install.sh

Backticks are deprecated. Curious, why prefer them here?

Clean up install.sh

---

src/index.rs

I noticed that we try to create the index database if there is any error opening the database, not just if the database isn't found. If we don't get a not found error, we should probably report it instead of trying to create the index.

Only try to create the database if it wasn't found

---

docs/src/inscriptions.md

Update docs to include all fields, including content-encoding

---

src/subcommand/wallet/transaction_builder.rs

Fix coin selection.

---

deploy/save-ord-dev-state
docs/src/guides/teleburning.md
src/inscription_id.rs
src/subcommand/wallet/inscribe.rs

I fixed some typos on docs and comments.

Fix some typos

---

src/inscription.rs

Hide /content/<INSCRIPTION_ID> HTML inscriptions

---

.github/workflows/ci.yaml
docs/po/it.po
docs/theme/index.hbs
justfile

italiano Version of Ordinals Theory Handbook 
Translated by Cicero.sats
X account : https://twitter.com/cicero_sats 
Local run good, ready to merge.

italiano version of Ordinals Theory Handbook

---

batch.yaml

Fix batch docs

---

src/index.rs
src/subcommand/server.rs
src/templates/transaction.rs
templates/transaction.html
tests/server.rs

Show all inscriptions on /tx page, instead of just the first.

Show all inscription geneses on /tx

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/lib.rs
src/subcommand/server.rs

- Bump version: 0.13.1 → 0.14.0

Release 0.14.0

---

src/subcommand/wallet.rs

Fix wallet create

---

src/templates.rs

Enter beta

---

README.md

Fix Project Board link

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Bump version: 0.14.1 → 0.15.0

Release 0.15.0

---

docs/src/introduction.md

Remove dead video link

---

Cargo.lock
src/decimal.rs
src/lib.rs
src/outgoing.rs
src/subcommand/wallet/send.rs
test-bitcoincore-rpc/Cargo.toml
test-bitcoincore-rpc/src/api.rs
test-bitcoincore-rpc/src/lib.rs
test-bitcoincore-rpc/src/server.rs
test-bitcoincore-rpc/src/state.rs
tests/lib.rs
tests/server.rs
tests/wallet/inscriptions.rs
tests/wallet/send.rs

Add outgoing info and dry run when sending

---

src/subcommand/wallet/inscribe.rs
src/subcommand/wallet/inscriptions.rs
src/subcommand/wallet/send.rs
src/wallet.rs
src/wallet/inscribe/batch.rs
src/wallet/transaction_builder.rs
tests/lib.rs
tests/wallet/inscribe.rs

Fixes #2367, #3089 and #3094 
Closes #2368

Show reinscriptions in wallet output

---

Cargo.lock
Cargo.toml
crates/test-bitcoincore-rpc/Cargo.toml
src/wallet.rs
src/wallet/inscribe/batch.rs

Depends on https://github.com/ordinals/rust-bitcoincore-rpc/pull/17

Use vector in call to import descriptors

---

src/lib.rs

Needed for end-to-end usage of the event sender feature: https://github.com/mi-yu/ord-custom-indexer-example

Make Options public

---

docs/src/inscriptions/rendering.md
src/subcommand/env.rs

- Write a JSON file containing the bitcoind port, the ord port, the bitcoin-cli command, and the ord wallet command.
- When creating a wallet, also fund it.

Improve `ord env`

---

src/inscriptions/charm.rs
src/subcommand/server.rs
templates/inscription.html

Also don't display vindicated charm on inscription page.

Display inscription parent above metadata

---

src/runes/tag.rs

Fixes https://github.com/casey/runestone/issues/150.

Make nop and burn tags one byte

---

batch.yaml
src/subcommand/wallet/inscribe.rs
src/wallet/inscribe/batch_file.rs
tests/wallet/inscribe.rs

Add reinscribe option to batch file

---

crates/ordinals/src/sat_point.rs
src/wallet/inscribe/batch_file.rs

Check for duplicate satpoints in satpoint mode

---

src/runes.rs

This is a test case I missed in #3206.

Test that runes can be minted with no edict

---

src/wallet.rs
tests/wallet/balance.rs

add better error log for `ord server` is not running
Related #3263 #3269

refactor: better error message with without server running

---

docs/po/zh.po

Update zh.po to the newest version.
Local Test good.
Request to merge.

Chinese Version Update

---

src/subcommand/server.rs
src/templates/rune.rs
templates/rune.html

Make rune parent clickable

---

crates/ordinals/src/runestone.rs
docs/src/inscriptions/delegate.md

chore: fix typos

---

docs/src/runes.md

A small grammar fix while I was going through rune docs.

[minor] fix grammar.md

---

src/subcommand/wallet/mint.rs
tests/wallet/mint.rs

just an annoying leftover word from the recent change

fix leftover etch

---

docs/po/zh.po

updated Rune Section of the handbook;
fix some typo ;
fix some missed translation;
Propose a translation of "Rune" in Chinese of both ："符文"of literal translation and “福文🧧” of free translation.
福 means "blessing", "good fortune", or "good luck" but with same pronunciation with its literal translation.
Local test good, ready to merge 🫡

zh.po rune section updated

---

src/wallet.rs

Fixes #3479.
Also partially addresses #3436

Fix maturation loop

---

src/wallet.rs
tests/json_api.rs
tests/lib.rs
tests/runes.rs
tests/wallet/balance.rs
tests/wallet/batch_command.rs
tests/wallet/mint.rs

Fix off-by-one in wallet when waiting for etching commitment to mature

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Bump version: 0.18.0 → 0.18.1

Release 0.18.1

---

src/subcommand/wallet/batch_command.rs
tests/wallet/batch_command.rs

Forbid etching below rune activation height

---

src/subcommand/server.rs
src/templates/rune.rs
templates/rune.html
tests/lib.rs

Show premine percentage

---

src/subcommand/wallet/resume.rs
src/wallet.rs

clear etching when rune commitment is spent

---

docs/src/inscriptions/recursion.md

Making the format of the markdown consistent with the other recursive endpoints.

Update recursion.md with consistant syntax

---

src/subcommand/wallet/mint.rs
tests/wallet/mint.rs

Allow minting when mint begins next block

---

src/subcommand/wallet/cardinals.rs
tests/wallet/cardinals.rs

Do not show runic outputs in cardinals command

---

src/inscriptions/media.rs

Been inscribing a lot of mjs files.

JS extension for mjs files

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Bump version: 0.18.3 → 0.18.4

Release 0.18.4

---

src/index.rs

this is the code from @gmart7t2 to fix #3493 - I replicated the issue (in 0.18.5) and verified that this fixed it on my local.

Update index.rs to fix ord list command

---

docs/src/runes/specification.md

We should be clear about what happens when there aren't enough runes available to give the same amount to every output

Update runes spec

---

docs/src/inscriptions/recursion.md

When adding an example for #3771 I noticed that this example was in the docs twice. So I deleted one of them.

Remove duplicate example

---

Cargo.lock
Cargo.toml

Add -dev suffix to version

---

src/subcommand/server.rs
src/templates/inscription.rs
templates/inscription.html

fixes #3199 
I didn't add the degree, though.  Please let me know if that is still desired and if you think it should be in a separate PR or not.

adding sat name to inscription page

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/mockcore/Cargo.toml
crates/ordinals/Cargo.toml
justfile
src/subcommand/server.rs

- Bump version: 0.18.5 → 0.19.0

Release 0.19.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/audit-cache/Cargo.toml
crates/audit-content-security-policy/Cargo.toml
crates/mockcore/Cargo.toml

- Bump version: 0.19.0 → 0.19.1

Release 0.19.1

---

docs/po/zh.po
src/inscriptions/envelope.rs
src/wallet/batch/plan.rs
tests/lib.rs

Add **"Sat Hunter "** section 
Delete **"#, fuzzy"** error
Local Tested , Request to merge

updated ZH.PO 

---

src/subcommand/server.rs

for #3875 - adding the sat_balance for the address to the address API

adding sat_balance to address api

---

src/index.rs
src/index/updater.rs
src/index/updater/inscription_updater.rs
src/lib.rs
src/subcommand/server.rs
src/templates/status.rs
templates/status.html
tests/json_api.rs

These make the status page massive and ugly.

Remove content type counts from /status page

---

src/subcommand/server.rs
src/templates/iframe.rs

Allow scrolling in iframe

---

src/subcommand/server.rs
src/templates/inscription.rs
templates/inscription.html
tests/server.rs
tests/wallet/batch_command.rs
tests/wallet/send.rs

Add `/satpoint/<SATPOINT>` endpoint

---

src/index.rs
src/subcommand/server.rs

Fix non-existant output lookup

---

Cargo.lock
Cargo.toml

Revert redb to 2.1.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml
justfile

- Bump version: 0.21.1 → 0.21.2

Release 0.21.2

---

Cargo.lock
Cargo.toml

Redb issues possibly fixed! See https://github.com/cberner/redb/issues/879
Testing on charlie now.

Un-pin redb dependency and update to 2.2.0

---

crates/ordinals/src/charm.rs
crates/ordinals/src/sat.rs
src/templates/sat.rs

Add palindrome charm

---

Cargo.toml
README.md

Update minimum rust version

---

crates/ordinals/src/charm.rs

add missing `palindrome`

---

crates/ordinals/src/charm.rs

Ensure that issues like #4103 can't happen again.

Test `Charm` `FromStr` implementation for exhaustiveness

---

src/wallet/wallet_constructor.rs
tests/wallet/balance.rs

Better error message for wallet sync

---

crates/audit-content-security-policy/src/main.rs

Fix content security audit binary

---

docs/src/bounty/3.md

Hi,
I noticed a -possible- typo in this text.
"Popularity is the font of value"
"Font" should likely be "fount," as "fount of value" is the correct phrase.
Corrected: "Popularity is the fount of value"
Thanks.

Possible typo here: 3.md

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/mockcore/src/server.rs
src/index.rs
src/index/updater/rune_updater.rs
src/into_u64.rs
src/lib.rs
src/subcommand/wallet/batch_command.rs
src/wallet.rs

- Bump version: 0.22.2 → 0.23.0

Release 0.23.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

- Bump version: 0.23.0 → 0.23.1

Release 0.23.1

---

crates/audit-cache/src/main.rs
crates/mockcore/src/server.rs

fixed 2 minor but obvious typos

chore: fix minor typos

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/mockcore/src/wallet.rs
src/index/updater/rune_updater.rs
src/inscriptions/envelope.rs
src/wallet/batch/plan.rs

- Bump version: 0.23.1 → 0.23.2

Release 0.23.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/mockcore/src/lib.rs
crates/ordinals/src/pile.rs
crates/ordinals/src/sat.rs
src/decimal.rs

- Bump version: 0.23.2 → 0.23.3

Release 0.23.3
