ordinals/ord

docs/index.html
This uses the `defer` attribute to allow placing the script tag in `<head>`: https://caniuse.com/script-defer
=> Put script tag in head with defer

src/arguments.rs, src/nft.rs, src/subcommand/verify.rs
1. Nft has that information (implicitly, since it can be derived from nft.data).
2. vec u8 ensures hash stability
=> Remove data_hash from metadata and make metadata a Vec<u8>

bip.mediawiki, tests/find.rs
Change slot notation to `AxBxCxD` where:
A = Block height
B = Index of transaction in block
C = vout
D = Offset of ordinal in output
=> Change slot notation to AxBxCxD

src/subcommand/server.rs, tests/server.rs
From now on, endpoints returning raw JSON should be under /api/
=> Move /list endpoint to /api/list

deploy/setup
The script installs bitcoind, so this note isn't necessary.
=> Don't warn about installing bitcoind in deploy/setup

src/epoch.rs, src/height.rs, src/index.rs, src/main.rs, src/subcommand/server.rs, src/subcommand/server/templates.rs, src/subcommand/server/templates/clock.rs, src/subcommand/server/templates/home.rs, templates/clock.svg, tests/server.rs
The SVG is adapted from this extremely helpful tutorial by John O. Paul:
https://medium.com/the-andela-way/create-a-pure-css-clock-with-svg-f123bcc41e46
=> Add a clock

src/index.rs, tests/list.rs, tests/server.rs
=> Don't write to OUTPOINT_TO_TXID table

src/ordinal.rs, src/subcommand/server/templates/ordinal.rs, templates/ordinal.html, tests/server.rs
Height is less understandable than block, and time is unambiguous, so "block time" isn't necessary.
=> Improve names for a couple of properties

src/subcommand/server.rs
It's good practice to provide a ACME contact email, so they can contact
you about issues with your cert, but not required, so let's make it
optional as well.
=> Make --acme-contact optional

deploy/ord.service, src/bytes.rs, src/index.rs, src/main.rs, src/options.rs
The ordinal index, stored in <ORD_DATA_DIR>/index.redb, is a redb
database, which grows dynamically. However, the maximum size that the
database can grow to must be declared up-front, to avoid expensive
region allocation operations on insert. We've been using 10 MiB as the
default index size, which is too small for anything but testing.
This commit changes the default maximum index size to 1 TiB on mainnet,
testnet, and signet, and leaves it at 10 MiB on regtest. 1 TiB is more
than needed, as even the mainnet database is only ~50 GiB, but
allocating a database is fast enough, so it doesn't hurt to over
provision and not have to think about it. For testing though, which is
done with `--chain=regtest`, we want database allocation is fast, and 10
MiB is more than enough.
=> Increase default maximum index size for non-regtest chains

README.md
@raphjaph I wanted to make sure to actually document this, since it's not obvious at all. Logging is actually pretty configurable, since it uses `env_logger`.
=> Document how to turn on logging

src/subcommand/server/templates/clock.rs, templates/clock.svg
This PR is just to show that the SVG has to be scaled up because the text element for the block height is squished. I don't know if there is another way to fix the text but I've tried using `font-size="10%"`,`font-size="0.1em"`, `font-size="xx-small"` and `font-size=10px`. I've also specified `font-weight=1` (thinnest possible lettering). 
I think the SVG has to be scaled up 2-3x for the text not to look squished but if there is another solution I'm happy to use that as well.
=> added blockheight to SVG

bin/benchmark, justfile
The way this was being done before relied on `./bin/benchmark {{dir}}` not resulting in an argument being passed when `dir` is `""`, which is a somewhat unintuitive side effect of the way `just` evaluates recipe lines. Changing it so it always passes in  the directory argument.
=> Pass benchmark dir name in justfile recipe

src/index.rs
Minor logging improvement so we can track how far we had to backoff
=> Log retry interval

src/index.rs
Fixes #417. I want to double check first that redb implements the fixed-size optimization for byte arrays.
=> Use fixed-size types for database keys and values.

Cargo.lock, src/index.rs, tests/info.rs
I'm unsure about how to properly store a single value persistently in the database. In its own table? What should the key be? Or I make a table HEIGHT_TO_NUM_OUTPUTS that tracks how many outputs there are per block and then I just add up those values in the `info` command?
#487
=> Store and count the total number of outputs traversed when building the index

src/subcommand/server.rs, tests/server.rs
Finishes #513
Should #520 and #490 be added to this PR?
To Do:
=> add ordinal searching through path: /search/QUERY

src/index.rs, src/subcommand/find.rs, src/subcommand/index.rs, src/subcommand/list.rs, src/subcommand/server.rs, src/subcommand/wallet/identify.rs, src/subcommand/wallet/send.rs
It's never useful to have an unsynced index, so do it on open, and rename `Index::index_ranges` to just `Index::index`.
=> Update index in `Index::open`

Cargo.lock, Cargo.toml
Building `ord` was failing with:
```
cargo build
Updating git repository `https://github.com/casey/redb.git`
error: failed to get `redb` as a dependency of package `ord v0.0.3 (/home/satoshi/code/ord)`
Caused by:
failed to load source for dependency `redb`
Caused by:
Unable to update https://github.com/casey/redb.git?branch=add-write-lock#36a470cc
```
Looks like that branch was merged into the main `redb` repo and was automatically deleted, and `0.7.0` was released which includes the changes from the branch.
=> Update redb version to 0.7.0

src/subcommand/server.rs
Not really that important, but this struck me as being superfluous, and it was easy to remove.
=> Remove /clock.svg route

Cargo.lock, Cargo.toml, tests/command_builder.rs, tests/find.rs, tests/lib.rs, tests/list.rs, tests/parse.rs, tests/server.rs
=> Add server integration test

docs/content/bounty/0.md, docs/content/bounty/2.md
Since the bounties are now on a different domain, they need full URLs to any URLs on ordinals.com
=> Fix bounty links

.gitignore
`tmp` is created by the `release` recipe, this just adds it to `.gitignore`.
=> Ignore temporary directory

src/subcommand/server/templates/ordinal.rs, templates/ordinal.html
Fixes #400. Order time-based properties from least frequent to most frequent. Also group percentile with decimal/degree/name, because like them, it unambiguously refers to an ordinal.
=> Sort ordinal properties

src/index.rs
This speeds up a full test run from ~4.6 seconds to ~3.3 seconds.
=> Speed up tests by using redb::Durability::None

src/subcommand/server.rs, src/subcommand/server/templates/home.rs, templates/home.html
The additional information looks a little better under a dedicate header:
=> Add status header to homepage

src/subcommand/server.rs, src/subcommand/server/templates.rs, src/subcommand/server/templates/home.rs, static/index.css, templates/home.html, templates/page.html
Add a navigation bar to the top of every page with links and the search box.
=> Add a navigation bar

book/book.toml, book/src/SUMMARY.md, book/src/theory.md, src/subcommand/server.rs, src/subcommand/server/templates/home.rs, static/index.css, templates/home.html
- Add description of name encoding on theory page
- Vertically align contents of nav bar and make logo bold and white
- Don't color block links on homepage by rarity (in practice, they're always an ugly green color)
- Use CSS variables for colors
- Use `coal` as the default theme for the book
- Style the site with `coal` theme colors (we can change this later, I just want both to be the same color)
=> Misc docs fixes

src/index.rs, src/options.rs, src/subcommand/server.rs
This is what bitcoin core does, and allows running instances of `ord` on different networks with the same argument to `--data-dir`.
=> Append network to data dir

src/chain.rs, src/main.rs, src/subcommand/rune/publish.rs
Previously, we were using https://ordinals.com as the default publish URL, regardless of `ord`'s current network.
=> Use https://signet.ordinals.com as default signet publish URL

src/index.rs, src/index/rtx.rs
Splitting this out from PR #653.
=> Make table names more explicit

src/subcommand/wallet/transaction_builder.rs
- Add should-panic checks to ensure they're operating correctly
- Add invariant messages to all expects and asserts
- Refactor build checks to operate on the built transaction, instead of the builder. This seems better, since if we mess up transaction construction somehow, but the builder is okay, this would catch that case
=> Improve transaction builder checks

src/subcommand/wallet/transaction_builder.rs
I refactored the tests to use helper functions to generate outpoints, addresses, transaction inputs, and transaction outputs. This makes them way more compact and easier to read.
=> Add helpers to make transaction builder tests more concise

src/subcommand/server/templates/clock.rs, templates/clock.svg
Apparently you're supposed to do this.
=> Add encoding declaration to clock SVG

src/subcommand/wallet/transaction_builder.rs
It's probably better to over-estimate fees than to under-estimate fees, so assume that all inputs are P2PKH inputs. The worst case would be a P2SH multisig, but those are much rarer, so use P2PKH since it's the worst of the most common input types.
=> Use worst-case fee estimates

src/index.rs
- Set initial position correctly
- Only increment if we're not done
- If the position is greater than the length, update the length
- Clear the progress bar once we're done
=> Improve progress bar

src/chain.rs, src/subcommand/wallet/send.rs, tests/wallet.rs
Addresses encode the network that they are valid for. Check this, so that it's not possible to send to, for example, a signet address on mainnet.
=> Ensure that send addressess are valid for current network

src/index.rs, src/ordinal.rs
Working on #371 starting with a trivial improvement:
Replace check for uncommon or better rarity by specialized, more efficient method. This line in index_transaction accounted 70% of the time in index_transaction, so it's worth the more verbose, less general method.
There's more potential here, as self.epoch() can likely be sped up significantly - the binary search takes an inordinate amount of time still.
=> Make index faster by faster checking for uncommon or more rare ordinals

Cargo.lock, Cargo.toml, src/index.rs, src/index/updater.rs
=> Background block fetch

src/index.rs, src/subcommand/server.rs, src/subcommand/server/templates/block.rs, src/subcommand/server/templates/ordinal.rs, templates/block.html, templates/ordinal.html
Not sure about this since it's additional clutter, but really like it from a pedagogical point of view, since I think the idea of a difficulty target is most easily understood by seeing it along with block hashes.
=> Show difficulty target on block page

src/subcommand/server.rs, src/subcommand/server/templates.rs, templates/page.html
=> Display chain in header

src/index.rs, src/index/updater.rs
Parsing inscriptions might be responsible for a performance regression, per #798, making indexing the mainnet chain much slower. We don't want to enable inscriptions on mainnet anyways, so for now, just disable looking for them on mainnet.
There might be a performance issue here, but I'm confident that it can be fixed, so we can punt on it and deal with it later.
=> Disable inscriptions on mainnet

README.md
=> Add minimum system requirements to readme

justfile
`just build-snapshots` will build snapshots of the index every 50,000 blocks in `tmp/snapshots` and record the time in seconds that each one took to build in `tmp/snapshots/time.txt`.
=> Add build-snapshots recipe

src/index.rs, src/index/updater.rs, src/main.rs, src/subcommand/info.rs, src/subcommand/server.rs, tests/info.rs
Store this information in the database for each commit, so we don't need to look at log files to get this information, we can just look at the index.
Also convert `info` command output to JSON, so we can represent data with nested fields.
=> Record commit start block count and timestamp

deploy/ord-dev.service, deploy/ord.service, src/index.rs, src/index/updater.rs, src/options.rs, src/subcommand/server.rs, tests/find.rs, tests/index.rs, tests/info.rs, tests/list.rs, tests/server.rs, tests/test_server.rs, tests/wallet.rs
Some concerns with leaving this stuff in place behind a flag:
- extra subcommands in help (find, list, info)
- updater becomes a little more complicated (not incredibly bad though)
- have to maintain and test two configurations (for example, just have tests that exercise error messages when flag is not passed)
jk who cares, we can deal with those problems if and when they come up
=> Only index ordinals if `--index-ordinals` is passed

src/index/updater.rs
This isn't strictly correct, since we should also request transactions when we're looking for inscriptions, but this is a simple first step towards fixing #838. With this change, building the index drops from ~1.5 hours to ~2 minutes on my macbook, and from ~12 hours to 9 minutes on ordinals.com.
=> Only request transactions when building ordinal index

src/subcommand/wallet/send.rs, tests/lib.rs, tests/wallet.rs
=> Send by inscription ID

src/chain.rs, src/inscription.rs, src/subcommand/wallet/inscribe.rs, tests/wallet.rs
Signet and testnet are both low-volume networks without a functioning fee market. Because of the potential for spam, we don't want to allow large inscriptions on those networks. Set the size limit to 1024 bytes for both signet and testnet, which is large enough that we'll exercise the content data chunking, but small enough that spam shouldn't be an issue. Regtest is a private test network, so spam is not an issue, and mainnet has a robust fee market, so large inscriptions will have to pay correspondingly high fees.
=> Set size limit to 1024 on signet and testnet

src/epoch.rs, src/index.rs, src/index/updater.rs, src/main.rs, src/ordinal.rs, src/subcommand/wallet/inscribe.rs
Casts using `as` often silently truncate, so turn on lints that disallow them and avoid them.
=> Avoid `as` conversions

src/inscription.rs, src/subcommand/wallet/inscribe.rs, tests/wallet.rs
=> allow inscribing without specifying satpoint

docs/src/guides/inscriptions.md
=> Mention that wallets do not need to be loaded after being created

src/inscription.rs, src/test.rs
We want instruction parsing to be simple and stable, so that it is easy to maintain consensus over the set of valid inscriptions.
This changes the inscription parser to be simpler and more generic:
- Unknown fields are ignored
- All fields can be omitted
The only hard errors are:
- Missing magic number
- Non-push instruction
- Duplicated field
=> Make instruction parsing field agnostic

src/inscription.rs, src/inscription/content_type.rs, src/main.rs, src/subcommand/server.rs, tests/wallet.rs
Added all common and widely supported image content types. Many of them have improved compression, which make them interesting for resource constrained inscriptions.
I was going to add avif, but it isn't widely supported yet: https://caniuse.com/?search=avif
=> Support more image content types

src/content.rs, src/inscription.rs, src/inscription/content_type.rs, src/subcommand/server.rs, src/subcommand/server/templates/content.rs, static/index.css, tests/server.rs
This was easier than I thought. This serves all content with a CSP header value of `default-src 'none'`. When content is loaded in an iframe with this CSP, all outgoing requests from the iframe are disallowed. We can then serve SVG and HTML content in frames, and they can't make outgoing requests, lessening security concerns and avoiding breakage and references to off-chain content.
=> Support SVG and HTML inscriptions

src/subcommand/server/templates/content.rs, src/subcommand/server/templates/inscription.rs, static/index.css, tests/wallet.rs
Without 101% width and height I was getting a weird issue where SVG inscriptions on the main page would display with a white border on one side.
=> Add white background to inscription content

src/subcommand/wallet.rs, src/subcommand/wallet/balance.rs, tests/wallet.rs
Add a simple balance command. Here's what it looks like:
```
$ ./target/debug/ord --signet wallet balance
0.0099852 BTC
```
closes #1036
=> add balance command

quickstart/macos
I thought that a script with all the commands needed to get started on macos would be useful. We should probably link to it in the docs.
=> Add quickstart script for macos

Cargo.lock, Cargo.toml, src/index.rs, src/index/rtx.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs
I haven't finished benchmarking the mmap backend against the new safe one, so I left ord using the mmap backend.
=> Upgrade to redb 0.11.0

static/index.css
This improves the look of text without hard line wraps, but makes text with hard line wraps look much worse, so I think we should remove it.
We should encourage inscription authors to use HTML or markdown if they don't want hard line breaks. Since omitting all tags is allowed in html, you can publish just the text, no need for `<html>` or anything else.
=> Remove wrapping on text inscriptions

Cargo.lock, Cargo.toml, src/main.rs, src/subcommand/server.rs, test-bitcoincore-rpc/Cargo.toml
I forget why we added CORS headers in the first place. They're easy to add back, so let's just remove it until we're sure we actually need them.
=> Remove CORS headers

src/chain.rs
Made an inscription on testnet in [tx 0a1b4e4acf89686e4d012561014041bffd57a62254486f24cb5b0a216c04f102](https://mempool.space/testnet/tx/0a1b4e4acf89686e4d012561014041bffd57a62254486f24cb5b0a216c04f102), at height 2413343, so this PR updates `Chain::first_inscription_height`.
=> Add testnet first inscription height

docs/src/guides/inscriptions.md, src/options.rs, src/subcommand/wallet/inscribe.rs, tests/lib.rs, tests/server.rs, tests/wallet.rs
=> Add short flags

src/inscription.rs
Fixes #1046. This doesn't add a version, but allows us to add one in the future. We can add a version field with an even tag, which will render it invalid for old clients, allowing for future upgrades.
=> Unrecognized even fields render inscriptions invalid

install.sh
I copied this from just, and it needed modifications.
- Removed the windows target. It's broken in Just's install.sh, which indicates that the script has never been run on windows T_T
- Fixed x86 linux target
=> Fix install script targets

src/subcommand/server.rs, src/templates.rs
Might as well, now that Boilerplate works with generics
=> Make PageHtml generic over PageContent type

src/index.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/subcommand/server.rs, test-bitcoincore-rpc/src/lib.rs, test-bitcoincore-rpc/src/state.rs
@raphjaph This is a truly horrific PR, but I wrote a bunch of tests and tested it from a few angles and I think it works.
This does a few things:
- Tracks inscriptions that are spent to fees
- Tracks inscriptions that are spent to fees that are then underpaid (thus destroying the sat). These have their locations updated to a satpoint consisting of a null outpoint, with an offset which increments as sats are lost
- Tracks rare sats that are spent to fees
=> Fee-spent but unlost inscriptions

src/subcommand/wallet/transactions.rs, test-bitcoincore-rpc/src/api.rs, test-bitcoincore-rpc/src/server.rs
This was failing when run against an actual Bitcoin Core node. I'm not sure what the real limit is, but u16::MAX seems to be okay, and u32::MAX failed, so I used a u16.
=> Fix limit max

justfile
`/var/lib/ord-dev/**/index.redb` wasn't hitting `/var/lib/ord-dev/index.redb`, so add that case explicitl.
=> Remove mainnet ord-dev index

src/options.rs, src/subcommand/wallet/create.rs, src/subcommand/wallet/inscribe.rs, tests/wallet.rs
We're removing these soon, and they complicate #1158, so let's just get rid of them now.
=> Remove mainnet restrictions

src/templates/home.rs, src/templates/iframe.rs, src/templates/inscriptions.rs, src/templates/output.rs, src/templates/sat.rs, static/index.css, templates/home.html, templates/inscriptions.html, templates/output.html, templates/sat.html, templates/transaction.html, tests/server.rs
Fixes #1194.
Changes the `inscriptions` class to `thumbnails`, to be more descriptive, and uses it wherever we're displaying inscriptions. Makes links on output pages clickable.
=> Fix thumbnail links

.github/workflows/ci.yaml
It's not a very important check, so we can just skip it on CI.
=> Don't check lockfile on CI

src/inscription.rs, src/media.rs, src/subcommand/server.rs, src/templates/inscription.rs, src/test.rs, templates/inscription.html, tests/server.rs, tests/wallet/send.rs
This fixes an issue where old inscriptions on signet with no body had previews containing error messages.
Changes the `media` function to return `Media::Unknown` if:
- There is no body, since trying to preview an inscription with no body would return a 404.
- The content type is unknown or otherwise invalid, since we don't know what it is.
`/content` will still return a 404 for an inscription with no body.
=> Empty preview

src/subcommand/server.rs
=> Search bar supports inscription id

templates/clock.svg
If the genesis mark is red, it looks like it's related to the red second hand. Make the genesis mark always orange, not just on hover. Also add a tooltip to the height.
=> Make genesis clock mark orange and add tooltip to height

static/index.css
Display thumbnails oldest on the left, newest on the right. This makes left/right order consistent with navigation keys.
=> Display newest thumbnails on right

static/index.css
Fixes #1320. I did this so that left and right arrows would be consistent with thumbnail order, but @haribosan thought it was confusing, and I'm inclined to agree, so let's revert it.
=> Un-reverse thumbnail row order

src/subcommand/server.rs
This still doesn't seem to do anything for Chrome, but it causes Firefox to cache content, so it can be merged, since at least we can see it doing something somewhere.
=> Add cache control headers to content responses

static/index.css
The inscription nav arrows on iOS Safari require two taps to activate. This seems to be related to opacity 0, so I changed it to use the color to hide the arrows instead. This now allows them to be activated in a single tap on Safari.
=> Allow single tapping nav arrows on iOS Safari

src/blocktime.rs, src/index.rs, src/index/updater.rs, src/lib.rs, src/subcommand/server.rs, src/templates/block.rs, src/templates/inscription.rs, src/templates/sat.rs, static/index.js, templates/block.html, templates/inscription.html, templates/sat.html, tests/server.rs
Display timestamps as UTC datetime strings. Add local time titles using JS.
=> Improve timestamps

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Release 0.4.1

src/lib.rs, src/rarity.rs, src/sat.rs, src/sat_point.rs, src/subcommand.rs, src/subcommand/wallet.rs, src/subcommand/wallet/balance.rs, src/subcommand/wallet/inscriptions.rs, src/subcommand/wallet/outputs.rs, src/subcommand/wallet/receive.rs, src/subcommand/wallet/sats.rs, src/subcommand/wallet/send.rs, src/subcommand/wallet/transactions.rs, tests/lib.rs, tests/wallet/balance.rs, tests/wallet/inscriptions.rs, tests/wallet/outputs.rs, tests/wallet/receive.rs, tests/wallet/sats.rs, tests/wallet/send.rs, tests/wallet/transactions.rs
=> JSON output for `wallet` commands

src/index.rs, tests/server.rs
> Q. How can you tell economists have a sense of humor?
> A. They use decimal points.
Fixes #1383.
=> Round expected sat timestamps to the second

deploy/ord.service
So I can stick ordinals.com behind cloudflare.
=> Remove redirect

justfile
I configured {signet.,testnet.,}ordinals.net  to serve the explorer instances, for a few reasons:
- Cloudflare blocks SSH traffic. Having the .net domains allows us to SSH directly into our origin servers.
- Our proxied servers can't get certificates for the .com domains. Having the .net domains allows them to get .net certifcates, which allows us to configure cloudflare to use encryption when connecting to the origin servers.
- The .net domains give us a backup in case something goes wrong with cloudflare proxying.
- We can compare what's served at .com and .net domains to figure out what cloudflare is doing.
=> Use unproxied domains in justfile recipes

shell.nix
Add missing 'pkg-config openssl' so nix can run `cargo test`
=> nix: make it such that cargo test will run on nix

docs/src/SUMMARY.md, docs/src/guides/collecting.md
@windsok @VirtuallyThere First draft of a simple guide, which links to @windsok's gist on making a `ord`-compatible Sparrow wallet.
I was saying "rare sats and inscriptions" everywhere, so I just used "ordinals" because it's simpler.
=> Add collecting guide

src/media.rs
Add `model/stl` with extension `.stl` to `Media::TABLE` with type `Media::Unknown`. This will allow using`.stl` files with `ord wallet inscribe`. However, they will not have any preview, since the media type is still unknown.
A follow-up PR can add some kind of rendering/preview support.
=> Support STL inscriptions

src/subcommand/preview.rs, src/subcommand/wallet/inscribe.rs, tests/wallet/inscribe.rs
Closes https://github.com/casey/ord/issues/1487.
=> Add commit-fee-rate option for specifying individual fee rates

src/subcommand/server.rs
I saw this error in the logs repeatedly, and was curious what inscription it was.
=> Include inscription ID in text inscription decode error

src/options.rs
These are common errors, so we should improve the error messages. Errors from `Option::cookie_file` are probably rare, but add some context since it can't hurt. Errors from `Client::new` are probably really common, and including the cookie file path should make what's going on much clearer.
=> Improve error messages related to cookie file

src/subcommand/preview.rs, src/subcommand/wallet/inscribe.rs, tests/wallet/inscribe.rs
=> flag that allows no W/U limit

deploy/bitcoin.conf
If the mempool grows above 300 megabytes, the default size, our node will start dropping transactions. I'd like to keep everything in the mempool, so increase the size to 1024 megs. (can fit at least 256 four meggers)
=> Increase deployed mempool size to 1024 megabytes

README.md
Added build commands using Cargo as well as the command to install Rust.
=> Add Build Instructions

.prettierignore
Will follow up with specific settings in a separate PR, but this disables prettier for those who have it enabled on save as discussed in #1586.
`prettier -c .` output before:
```
Checking formatting...
...(truncated)...
[warn] Code style issues found in 35 files. Forgot to run Prettier?
```
`prettier -c .` output after:
```
Checking formatting...
All matched files use Prettier code style!
```
=> Add prettierignore for all files

docs/src/guides/inscriptions.md, src/subcommand/wallet/inscribe.rs, src/subcommand/wallet/send.rs, tests/server.rs, tests/wallet/inscriptions.rs, tests/wallet/send.rs
Implement issue #1747 
Given high fee environment many users run into issue with default fee rate of 1. 
Review checklist:
=> Remove default for parameter `--fee-rate` for `wallet send`

install.sh
add additional err msg to build from source for users who's arch falls outside of the list (e.g. aarch64-Linux). Should help address https://github.com/casey/ord/issues/1628 and mitigate future issues on the topic.
```
case $uname_target in
arm64-Darwin) target=aarch64-apple-darwin;;
x86_64-Darwin) target=x86_64-apple-darwin;;
x86_64-Linux) target=x86_64-unknown-linux-gnu;;
*)
err 'Could not determine target from output of `uname -m`-`uname -s`, please use `--target`:' $uname_target
err 'Please try building from source: https://github.com/casey/ord#building'
;;
esac
```
=> install.sh case $uname_target: additional err msg

src/subcommand/wallet/inscribe.rs
The inscribe command would calculate the reveal tx fee incorrectly whenever the reveal tx wasn't funded by the first output of the commit tx as is the case when you inscribe on a satpoint with a non zero offset.
In such cases if the first output of the commit tx was much smaller than the 2nd the inscribe command would fail due to calculating a negative fee.
This commit fixes the problem and closes #1844.
=> Correct reveal tx fee calculation

src/lib.rs
Print a message saying that Ord has responded to a Ctrl-C event and will shut down immeidately with 5 Ctrl-C's.
=> Better interrupt message

src/subcommand/wallet.rs
Mark change addresses as change addresses and receiving addresses as receiving addresses rather than the other way around.
Closes #1801.
=> Fix the ord wallet descriptors

src/subcommand/wallet.rs, src/subcommand/wallet/cardinals.rs, tests/wallet.rs, tests/wallet/cardinals.rs
There's no easy way to find a list of cardinal outputs. You have to list all the outputs and remove the inscriptions. 
Hence: `ord wallet cardinals`.
=> Add "ord wallet cardinals" command to list the cardinal outputs.

src/index/updater.rs, src/lib.rs
This PR changes the amount of times the user has to hit Ctrl+C in order to kill the process from 7 to 2, this makes it easier for the user to immediately shutdown the process.
=> Handle interrupts better

README.md, install.sh, tests/wallet/cardinals.rs
- Remove defunct twitch stream link
- Reword readme
- Expand install script error message
- Remove comment in test
=> Misc changes

.github/workflows/ci.yaml, justfile
This PR switches `clippy` to `nightly`, both in ci scripts and for `just clippy` and friends. This is to workaround [this issue](https://github.com/clap-rs/clap/issues/4733), which I believe is fixed [here](https://github.com/rust-lang/rust-clippy/pull/10502), but hasn't landed in the stable version of `clippy`. This PR should be reverted once the fix lands.
Fixes #2035.
Of course this has some downsides:
- Nightly `clippy` is not stable, so we may have some CI issues introduced in newer nightly versions. (We could try to pin down `clippy` to an exact nightly version, which would avoid this. Any opinions?)
- CI caches get bigger.
- Before locally running `just clippy` (or e.g. `just ci`) you have to run `rustup install nightly`.
=> Switch to clippy nightly

docs/src/inscriptions.md
Technically should be a `OP_PUSHDATA1` but this is simplified overview.
=> `OP_PUSH` instead of `OP_1`

install.sh
The install.sh was still using casey/ord repo.
=> Updated install.sh for new repo name

Cargo.lock
Update the `ord` dependency in `Cargo.lock` to latest release.
=> Update ord dependency in lockfile

Cargo.lock, Cargo.toml, src/lib.rs, src/subcommand/server.rs, src/subcommand/teleburn.rs, src/teleburn_address.rs, src/templates/inscription.rs, templates/inscription.html, tests/lib.rs, tests/server.rs
In this PR:
- eth teleburn addresses now have checksums in them. Had to take a dependency on rust-crypto, but didn't take any eth-specific dependencies
- added the ethereum teleburn address to the inscription detail page
- tests!
=> Added checksum to eth address, added teleburn to inscriptions page

src/subcommand/server.rs, tests/server.rs
Modify inscription content security policy header to allow for requests to `/-/`-prefixed endpoints, and add a `/-/content/:inscription_id` endpoint to allow inscriptions to request the content of other inscriptions.
Two CSP headers are required because it is not possible in a single CSP header to specify a policy that restricts requests to sub-paths of the current origin. So, we use two CSP headers, one to limit requests to `'self'`, the current origin, and one to limit requests to `*:*/-/`, the `/-/` sub-path of any origin. Browsers check both CSP headers, which has the net effect of restricting requests to the `/-/` sub-path of the current origin. 
Restricts requests to `/-/` instead of `/content/` because we may wish to add more endpoints that inscriptions can access, for example …
=> Recursive inscriptions

src/subcommand/server.rs, tests/server.rs
This PR is to allow HTML/JS inscriptions to use Blob urls by adding it to the Content Security Policy headers.
I am creating a javascript inscription where I draw some stuff onto a canvas, then convert that canvas into a HTML img. I have successfully done this with the following JS code:
```javascript
let canvas = document.createElement('canvas')
// Draw stuff onto canvas...
let img = document.querySelector('img')
img.src = canvas.toDataURL('image/png')
```
This works because `data:` is included in the Content Security Policy, so data urls are allowed. However, many sources state that blob urls should be used over data urls because they are more performant. So, I would like to do something like this:
```javascript
let canvas = new OffscreenCanvas(1024, 1024)
// Draw stuff onto canvas... …
```
=> Add blob urls to Content Security Policy headers

src/media.rs
Markdown is a desirable media type to add now that we are inscribing Libraries. 
This would be a good way to document code onchain. 
You could keep the documentation in the same UTXO as the library or create a child parent using the library inscription
Clients would probably need to create a recursive markdown parser to add links and images for instance.
`[link](<inscriptionId>)`
`![Image](<inscriptionId>)`
People could even make clients like obsidian using the same recursion above.
This would also allow people to easily write a blog on inscriptions.
=> add Markdown media type

src/chain.rs, src/index.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/inscription.rs
This fixes https://github.com/ordinals/ord/issues/2202
=> Fix Edge Cases in Cursed Inscription Numbering Leading to rare Off-by-One-Bug

src/subcommand/server.rs
Lower cache time to 600 (10 minutes) when an inscription is not found
Resolve issue #2232
=> Set lower max age for not found

src/index.rs, src/index/updater/inscription_updater.rs, src/subcommand/server.rs, src/subcommand/wallet/inscriptions.rs, src/templates/sat.rs, templates/sat.html
This PR fixes a bug in the assignment of reinscription sequence numbers and allows to correctly order reinscriptions in chronological order. It also implements showing all inscriptions for a given sat (and not just a random one) in the correct sequence.
=> Fix ordering for reinscriptions and show all reinscriptions for sat

src/index/fetcher.rs
Resolves: #2248 
Sometimes the transaction fetcher receives a non-json response from bitcoin core, resulting in a parsing error. It seems to happen due to load on the node. This is problematic because it will completely fail a batch of processed blocks. With the batch size set to 5000, if it fails a few thousand blocks in, it will be a lot of work to start over again.
This adds a retry which tries to fetch transactions with 5 retries which exponentially back off (Max being 3.2seconds).
=> fix: add retry to fetcher

src/index.rs, src/subcommand/wallet/balance.rs, src/subcommand/wallet/cardinals.rs, src/subcommand/wallet/inscribe.rs, src/subcommand/wallet/inscriptions.rs, src/subcommand/wallet/send.rs
This makes most ord commands run a few hundred times faster:
before:
```
$ time ord wallet balance > /dev/null
real	3m39.900s, user	0m23.681s, sys	0m20.880s
```
after:
```
$ time ord wallet balance > /dev/null
real	0m0.648s, user	0m0.025s, sys	0m0.199s
$ time ord wallet balance > /dev/null
real	0m0.477s, user	0m0.010s, sys	0m0.095s
$ time ord wallet balance > /dev/null
real	0m0.415s, user	0m0.021s, sys	0m0.067s
```
=> Only fetch inscriptions that are owned by the ord wallet

src/index.rs, src/index/reorg.rs
Height and depth are in the wrong order, leading to wrong log messages
=> Fix reorg typo

src/subcommand/server.rs
The `None` case of this match statement will never have an effect, since we do `body?` later one, which will case the whole function to return `None` if the body is empty.
=> Remove unused content_response match statement

src/index.rs
Implements #1893. This is a pretty straightforward optimization, so I think we should just implement it.
=> Allocate blocks vector ahead of time

src/inscription.rs, src/lib.rs, src/subcommand.rs, src/subcommand/decode.rs, tests/command_builder.rs, tests/decode.rs, tests/lib.rs
Decodes a transaction from a file, useful for debugging inscription parsing.
=> Add `ord decode` command

src/index.rs, src/index/updater/inscription_updater.rs
Fixes https://github.com/ordinals/ord/issues/2386
=> Make any zero-valued input inscription unbound

Cargo.toml, src/index.rs, src/index/entry.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/inscription.rs, src/inscription_id.rs, src/subcommand/server.rs, src/templates/inscription.rs, templates/inscription.html, test-bitcoincore-rpc/src/lib.rs, test-bitcoincore-rpc/src/state.rs, tests/json_api.rs, tests/wallet/send.rs
This is an initial PR implementing [draft spec](https://github.com/ordinals/ord/pull/2278/) for parent/child inscriptions. It only implements indexing parent inscriptions and displaying them on the front end and returning them from the JSON API.
Other features are not implemented and are deferred to a future PR:
- Creating inscriptions with parents in the wallet
- Displaying child inscriptions on the parent inscription page
=> Implement provenance in the index

docs/src/inscriptions.md, docs/src/inscriptions/provenance.md, docs/src/inscriptions/recursion.md
*NB: THIS SPEC IS NOT FINAL, NOT IMPLEMENTED, AND IS SUBJECT TO CHANGE AT ANY
TIME. IT SHOULD NOT BE CONSIDERED FINAL UNTIL IT MAKE IT INTO A PUBLISHED,
NUMBERED RELEASE OF `ord`. IF YOU CREATE INSCRIPTIONS BASED ON THIS IN-PROGRESS
SPEC, IT WILL PROBABLY CHANGE AND YOU WILL PROBABLY GET REKT.*
Add a draft provenance spec. Comments and suggestions are most welcome!
=> Provenance spec

src/index.rs, src/index/entry.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/subcommand/server.rs, src/templates/inscription.rs, src/templates/inscriptions.rs, templates/inscription.html, tests/json_api.rs, tests/server.rs, tests/wallet/send.rs
Adds an unstable sequence number to make some logic cleaner
=> Add sequence number

src/subcommand/wallet/inscribe.rs
the prevouts being used to construct the reveal signature is:
```rust
let mut prevouts = vec![unsigned_commit_tx.output[0].clone()];
if let Some(parent_info) = parent_info {
prevouts.insert(0, parent_info.tx_out);
}
```
but using `unsigned_commit_tx.output[0]` as one of its elements is a wrong assumption since a inscribe run can be called using `--satpoint` with offset > 0, which would make the first output of the commit transaction to be a change (part not used of the satpoint), and not the output encoding the taproot spending condition.
Example of a inscribe using `--satpoint=cad80aa153050fa300fc539e35fbb2046f4c99d3e09b27437db2232bfec43f71:2:1000`
(example produced building ord with the code from this pr. https://mempool.space/pt/testnet/tx/aab6b689ec23b60e0943adf6357eb3a2cdb8c50ebfaf10c …
=> fix  issue with `--satpoint` when offset > 0. (Fix #2465)

src/envelope.rs, src/index.rs, src/index/updater/inscription_updater.rs, src/inscription.rs
Now that we have the new envelope parser, this is very easy to do, so I thought why not. Finally recognize those early inscriptions which resulted from people manually creating inscriptions referring to our bad docs.
This would also allow us to save one byte per field ourselves by using a pushnum opcode instead of a pushbytes opcode.
=> Recognize inscriptions that use pushnum opcodes

src/sat.rs
Check after every digit if sat is out of range to avoid overflow.
=> Fix overflow in Sat::from_name

bin/package
This reverts commit fba065684f3a42ff3f447f2a7c6a8790da46a9bb. This was a good change, but requires coordination between the bin/package and install.sh. I'll open a new PR which contains the reverted change, along with the accompanying change to install.sh.
=> Revert "Fixes release tarbomb (#2473)"

src/runes/edict.rs, src/runes/runestone.rs
This also includes #2529, and you can see the third commit shows the size reductions, which are really nice. Will remove #2529 prior to merging.
=> Delta encode edict ids

src/index/updater/rune_updater.rs, src/runes.rs
Since it's so critical that we don't miss runes, it seems like a good idea to remove this special case. It also makes @rot13maxi's sophon a little bit cheaper to run, since he won't need to include an edict in the etchings.
=> Always create rune, even if none were allocated

src/index.rs, src/index/testing.rs, src/index/updater.rs, src/page_config.rs, src/runes.rs, src/subcommand.rs, src/subcommand/find.rs, src/subcommand/list.rs, src/subcommand/server.rs, src/subcommand/wallet/sats.rs, src/templates.rs, templates/page.html, tests/wallet/sats.rs
- Remove index checks in server, just return empty responses.
- Create all tables when index is created, so all index functions can be called, and will just return empty responses when the index doesn't exist.
- Add explicit checks to those command which don't make sense without an index.
This just cleans up the code a bunch.
=> Refactor index checks

src/subcommand/server.rs, src/templates/inscription.rs, templates/inscription.html
I think the `(unbound)` and `(unstable)` annotations are unattractive, so I removed them. Practically speaking, I think having `(unstable)` in large letters the inscription title makes cursed inscriptions unnecessarily unattractive and undesirable. `(unbound)` is also kind of unattractive, so I removed that too.
=> Remove paranthetical annotations

fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/runestone_decipher.rs, fuzz/fuzz_targets/transaction_builder.rs, fuzz/fuzz_targets/varint_decode.rs, fuzz/fuzz_targets/varint_encode.rs, justfile, src/lib.rs, src/runes.rs, src/subcommand/wallet/transaction_builder.rs
The `transaction-builder` fuzz target is broken, so I removed it from the recipe. I changed the fuzz testing recipe to run all the fuzz targets for a minute at a time. This allows splitting time evenly between targets.
=> Add rune fuzz targets

bin/package, install.sh
This puts the files in release archives inside a directory, so that when you extract them, they stay within a directory. This should be merged right before doing a release, so that the next release archive is compatible.
=> Create single-directory release archives

tests/server.rs
This test fails frequently, so I took a look. I think the issues it that we weren't waiting for the ord server to sync after mining a block. This should fix it.
=> Make server_runs_with_rpc_user_and_pass_as_env_vars test less flaky

src/subcommand/wallet/inscribe.rs
=> Requre --batch or --file for `ord wallet inscribe`

src/media.rs, static/preview-code.js
Add file type python closes  https://github.com/ordinals/ord/issues/1481
=> add python media type

src/index/updater/inscription_updater.rs
When logging re-inscription info, use already calculated `next_sequence_number` rather than calling `id_to_entry.len()`
On my PC (5600x, 32GB) speeds up indexing by ~40s per re-inscription.
=> Speed up indexing of re-inscriptions

src/subcommand/server.rs, tests/server.rs
closes #2603
quick little endpoint. open to change the path, or whatever other feedback folks have :)
=> Add metadata recursive endpoint

src/subcommand/server.rs, src/subcommand/server/error.rs
Error responses are currently cached by cloudflare, which is an attack vector. Someone could just watch mempool and make /content requests before the tx confirmation.
@raphjaph I am not able to get the tests to pass. Can you please point me in the right direction re: how to do this?
=> Avoid caching error responses

src/index.rs, src/subcommand/wallet/inscribe.rs, src/subcommand/wallet/inscribe/batch.rs, src/subcommand/wallet/send.rs, src/subcommand/wallet/transaction_builder.rs, test-bitcoincore-rpc/src/server.rs, tests/wallet/inscribe.rs, tests/wallet/send.rs
this is just a refactor of  #2563 on top of `master` now that everything is done through `Batch`.
=> have ord respect locked coins

src/runes/varint.rs
Nit. Simplify the varint code a bit. :))
=> Simplify varint encoding

src/index/fetcher.rs, src/index/reorg.rs
This client was timing out when commits took longer than 90 seconds, so just get a new client. This fixes #2455.
=> Use new RPC client in Reorg::get_block_with_retries

src/charm.rs, src/index/entry.rs, src/index/updater/inscription_updater.rs, src/inscription.rs, src/lib.rs, src/sat.rs, src/subcommand/server.rs, src/templates/inscription.rs, templates/inscription.html
Charms are cute emoji that appear on inscription pages. Charms include rarity charms, for inscriptions on rare sats, cursed inscriptions, inscriptions on block 9 sats, lost sats, unbound inscriptions, and reinscriptions.
=> Add inscription charms

src/index.rs, src/subcommand/server.rs, src/templates.rs, src/templates/collections.rs, static/index.css, templates/collections.html, templates/home.html
=> Implement /collections Page

Cargo.lock, Cargo.toml, src/index.rs, src/index/entry.rs
Also, `redb` now supports `char` index keys and values, so we no longer need to store it as a u32. Increments the schema version, since u32 -> char is a breaking change.
=> Update redb to 1.4.0

src/subcommand/index/export.rs
I think it's better not to have defaults for things like this. If we wanted it to work with `--tsv`, writing to stdout is the best option.
=> Remove default for `ord index export --tsv`

docs/src/inscriptions/recursion.md
=> Add docs and examples for sat recursive endpoint

tests/server.rs
This test is flaky on CI. Maybe ignoring it, so it runs alongside fewer tests, will help.
=> Ignore flaky test

src/envelope.rs, src/index.rs, src/index/updater/inscription_updater.rs
The envelope parser advances instruction by instruction, which causes the parser to advance too far when parsing inscriptions with the following structure:
```
OP_FALSE
OP_FALSE # checks for OP_IF, but skips instruction, so following inscription isn't recognized
OP_IF
"ord"
OP_ENDIF
```
```
OP_FALSE
OP_IF
OP_FALSE  # checks for "ord", but skips instruction, so following inscription isn't recognized
OP_IF
"ord"
OP_ENDIF
```
This adds yet another curse, the stuttering curse, for inscriptions with this structure.
@ipoh123 Have a look! Also, if there are any other issue you found, let us know! And, by the way, how did you find this?
=> Add stuttering curse

src/index.rs, src/index/testing.rs, src/subcommand.rs, src/subcommand/balances.rs, src/subcommand/server.rs, test-bitcoincore-rpc/src/server.rs, tests/balances.rs, tests/lib.rs
This is ready for review!
I'm not sure what the right output format should be. Should it be grouped by rune or grouped by output?
Grouped by output:
```json
{
"outpoint": {
"rune": "balance",
"rune": "balance",
},
"outpoint": {
"rune": "balance",
"rune": "balance",
}
}
```
Grouped by rune:
```json
{
"rune": {
"outpoint": "balance",
"outpoint": "balance",
},
"rune": {
"outpoint": "balance",
"outpoint": "balance",
}
}
```
Our not grouped at all:
```json
{
["outpoint", "rune", "balance"],
["outpoint", "rune", "balance"],
["outpoint", "rune", "balance"]
}
```
=> Rune balances

src/index.rs, src/index/updater/inscription_updater.rs, src/inscription.rs, src/subcommand/server.rs, src/subcommand/wallet/inscribe.rs, src/test.rs
=> Fix reinscription charm

src/subcommand/server.rs, src/templates/inscriptions_block.rs
* go to https://ordinals.com/block/800000
* it correctly shows "2914 Inscriptions"
* click "more" -> https://ordinals.com/inscriptions/block/800000
* it correctly shows the first 100 inscriptions
* click "next" -> https://ordinals.com/inscriptions/block/800000/1
* it incorrectly shows no inscriptions
Both `Server::inscriptions_in_block_paginated()` and `InscriptionsBlockHtml::new()` are removing the first `page_index * page_size` inscriptions. Only one of them should do it. 
This commit fixes the issue.
=> HTML endpoint /inscriptions/block/<height>/<page> returns nothing after page 0

crates/audit-cache/src/main.rs, deploy/checkout, deploy/setup, justfile, templates/page.html
This started with me trying to fix HTTP/2, and ended with me redeploying testnet and signet.
Because we now might need to deploy from branches on `casey/ord` or `raphjaph/ord` while developing, I added a `remote` argument to the deploy recipes, which takes a github repo that defaults to `ordinals/ord`.
This also updates the deploy script to install `curl`, which wasn't present on the VPS, and `locales-all`, which gets rid of a missing locale warning.
`testnet.ordinals.net` and `signet.ordinals.net` are now up.
=> Fix deploy setup script

deploy/setup
The status page is long now, so we should pipe it to /dev/null so it doesn't spam the terminal.
=> Don't print out status when deploying

justfile
Add a recipe for generating a code coverage report. Doesn't do much, but gives contributors a clue for how to do it. Our code coverage looks pretty good. I ran it, and our tests exercise 96% of our codebase by line.
=> Add coverage recipe

src/object.rs, src/representation.rs, tests/parse.rs
=> Add runes to parse command

deploy/ord.service
Add `--index-runes` to `ord.service`. Will only take effect on signet and testnet.
=> Index runes on servers

src/index/updater/rune_updater.rs, src/runes.rs
=> Allocate remainder when splitting runes

src/envelope.rs, src/lib.rs, src/subcommand.rs, src/subcommand/decode.rs, tests/decode.rs
Also add an optional compact output format which is less horrible to read
=> Decode transactions from core with `ord decode --txid`

src/inscription.rs
There are a bunch of non-HTML inscriptions with bodies containing `/content/<INSCRIPTION_ID>`, so hide them regardless of whether they're HTML or not.
=> Hide all inscriptions with /content/<INSCRIPTION_ID> content

src/index.rs, src/index/updater/inscription_updater.rs
=> Keep inscriptions with unrecognized even fields unbound after jubilee

deploy/ord.service, src/index.rs, src/index/updater.rs, src/options.rs, test-bitcoincore-rpc/src/lib.rs, test-bitcoincore-rpc/src/state.rs, tests/server.rs, tests/test_server.rs
First stab at storing transactions in the index. Doesn't have a flag to turn on and off, I wanted to rebuild the index first and see if it was faster.
=> Index transactions

src/index.rs
This PR adds progress bar for database repair. It doesn't work smoothly though: due to redb limitation, only 30%, 60% and 90% steps exist.
=> feat(redb): add repair progress

deploy/setup
Our deploy script currently doesn't work, because if you try to overwrite /usr/lib/bin/ord, it errors out since the file is being used. This uses `install` to move it into place, which also keeps one backup, which it names `/usr/local/bin/ord~`.
=> Use install to copy binary in deploy script

src/index.rs, src/index/updater/inscription_updater.rs, src/inscriptions/charm.rs, src/subcommand/server.rs, src/templates/inscription.rs, tests/json_api.rs
This PR adds a ❤️‍🔥 charm, named "vindicated". The intent is to demonstrate that, with only a small change to ord, we can support BRC-20 indexers that wish to update to a new version of `ord` at a later date, by letting them skip inscriptions with the vindicated charm until then.
This needs tests before being merged. We should also consider whether or not we want to make this charm visible to end users. Users may prefer not to have an additional charm on their inscriptions.
=> VINDICATION

src/index.rs
This should be faster, because we move the `map` until after `skip` and `take`, so that we don't map elements that we're going to skip.
=> Optimize get_inscription_ids_by_sat_paginated

src/subcommand/server.rs
This sets the max-age for cached responses to two weeks, instead of a year. It's probably better if these expire sooner, and we have to serve marginally more data, if weird responses eventually expire.
=> Cache less aggressively

src/wallet/inscribe/batch_file.rs, tests/wallet/inscribe.rs
Since in `same-sat` mode, the `destination` is also calculated by `get_change_address` as per [here](https://github.com/ordinals/ord/blob/4b95ff655aa051578d26d755ba1532819b1a9da5/src/subcommand/wallet/inscribe/batch.rs#L646), it's more correct to forbid `entry.destination` in `same-sat` mode.
=> chore: also forbid `entry.destination` in `same-sat` mode

src/index/updater.rs
The `index` object is already contained in `self`, so no need to pass it to an instance method, this also avoids referencing to the same object in two ways(`index` and `self.index`).
=> chore: remove index parameter from index_block

src/index/updater.rs
`range_cache` contains mapping of `output` to `sat ranges`, this also aligns the naming with other places.
=> chore: fix naming

src/inscriptions/media.rs
If you filter out browsers that don't matter, AVIF has pretty much universal support:
I think we should finally enable making AVIF inscriptions natively, since there's a huge jump in image quality.
=> Allow inscribing AVIF images

src/subcommand/wallet/restore.rs, tests/wallet/dump.rs, tests/wallet/restore.rs
Fixes issue #2990 by allowing a seed to be entered to stdin when restoring a wallet.  I'm not sure if I got the type coercion/checking exactly right here, so would appreciate any feedback/help.  Thanks!
=> add prompt for seed when restoring wallet

.gitignore, src/index.rs, src/index/event.rs, src/index/testing.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/lib.rs
Addresses https://github.com/ordinals/ord/issues/2789
Introduces a way for InscriptionUpdater to emit location update events on an in-process channel. Example usage can be found here: https://github.com/mi-yu/ord-custom-indexer-example
Copy of #2811 to allow edits by maintainers
=> Emit location update events to optional channel

static/preview-image.js, templates/preview-image.html
I think this is an improvement for all image formats and image types. `image-rendering: pixelated` is only important when upscaling pixel art. When upscaling other kinds of images, and when downscaling everything, `image-rendering: auto` is preferred.
This makes the image preview use `auto` rendering, when the body is less than the size of the image, A.K.A., downscaling.
This still leaves things suboptimal when upscaling non pixel art, but I can't think of a non-disruptive change to fix that.
=> Use `image-rendering: auto` when downscaling images

.gitignore, Cargo.lock, Cargo.toml, src/lib.rs, src/options.rs, src/subcommand.rs, src/subcommand/env.rs
Fixes #3135. I want to also finish #3145 before landing this, so that we can configure everything config file, so ord commands can be `ord --data-dir=env` and all flags are read from `env/ord.yaml`.
=> Add `ord env` command

docs/src/SUMMARY.md, docs/src/inscriptions/rendering.md, src/inscriptions/media.rs, src/lib.rs, src/subcommand/server.rs, src/templates/preview.rs, templates/preview-image.html
=> Use `image-rendering: auto` for AVIF inscriptions

src/index/updater.rs, src/options.rs, src/settings.rs
When using a low memory cloud server, I found that reducing the commit cache size can increase index speed.
[ordxscan](https://www.ordxscan.com/) mainnet ord index. 
Related #3158
=> Add commit interval

src/index/updater/rune_updater.rs, src/runes.rs, src/runes/runestone.rs, src/runes/tag.rs, src/subcommand/wallet/etch.rs, tests/wallet/send.rs
This PR changes claims from being a property of edict IDs, to being done with a dedicated tag.
This has a few advantages:
- Only one rune can be claimed at a time with a given runestone. Claim limits make claims costly because the claimant must pay transaction fees. If a given runestone can claim more than one rune, the the transaction fee is amortized across multiple claims. Making a claim a tag prevents this.
- The code for claiming with a claim bit is weird.
- If you want to claim a rune for the maximum amount, and send it to the default output, this can be done with a claim tag without needing an edict.
- The code is actually much cleaner.
I also finally refactored `RuneUpdater::index_runes` into multiple functions.
=> Encode claims with tag

README.md
ubuntu command wasn't working for me, found this one that works instead (ubuntu on windows)
=> update libssl-dev command

docs/src/guides/wallet.md, src/subcommand/wallet/restore.rs
=> Fix wallet restore and document

src/inscriptions/tag.rs
Add a `note` field to inscriptions. [chisel.xyz](https://chisel.xyz/) puts a note that the inscription was inscribed by chisel in tag 15. This seems reasonable, and similar to BitTorrent's `created_by` field. This PR adds the field to the `Tag` enum, to ensure we don't accidentally use it in the future. This field will probably never be displayed, since users probably don't want the tool which created the inscription to display on /inscription, and they can include that in the metadata if they do.
=> Add note field to inscriptions with tag 15

src/subcommand/env.rs, src/subcommand/wallet.rs, src/subcommand/wallet/receive.rs, tests/wallet/inscribe.rs, tests/wallet/inscriptions.rs, tests/wallet/receive.rs
Allow generating multiple addresses
Related #3275
1. `ord wallet receive`
```json
{
"addresses": [
"bcrt1pyeryjjzz5g2e2lxyf29z3j8kvpgr8ecas9cw2ttkyq8x9xhjhcus7ptp6e"
]
}
```
2. `ord wallet receive --number 2`
```json
{
"addresses": [
"bcrt1pt4a6xttm94j6pyp6dtstqu74axdv99vu00dfp0gwssmkgzymqh9q6c32gq",
"bcrt1pc9galhk22p6sdle5xp0ggsw5lxhcgttayr9unv8v97s9cf8ysdaqaa9h70"
]
}
```
3. `ord wallet receive -n 2`
```json
{
"addresses": [
"bcrt1pfjmvlll0ds3fhvnqp2ff4ymt5lncgpphgk3vmf795z0chdyqjytsvt5tuh",
"bcrt1p8xm6tzqy38cgrwpcg57fx4kh26kf337s758wrap0cy53kqep0nus34veyh"
]
}
```
=> feat: allow generate multiple addresses

bin/benchmark, bin/flamegraph, deploy/ord.service, docs/po/de.po, docs/po/es.po, docs/po/fil.po, docs/po/fr.po, docs/po/hi.po, docs/po/it.po, docs/po/ja.po, docs/po/ko.po, docs/po/pt.po, docs/po/ru.po, docs/po/zh.po, docs/src/guides/reindexing.md, docs/src/guides/settings.md, docs/src/guides/testing.md, src/index/testing.rs, src/options.rs, src/settings.rs, src/subcommand/env.rs, src/subcommand/server.rs, tests/command_builder.rs, tests/test_server.rs
=> Switch recommended flag usage from `--data-dir` to `--datadir`

src/index/updater/rune_updater.rs, src/runes.rs, src/runes/edict.rs, src/runes/rune_id.rs, src/runes/runestone.rs, src/subcommand/server.rs, src/subcommand/wallet/send.rs, src/test.rs, src/wallet/inscribe/batch.rs, tests/wallet/send.rs
- Make `Edict::id` `RuneId` instead of `u128`
- If an edict has an invalid id, the runestone is a burn
- If an edict has an invalid output, the runestone is a burn
=> Make edicts stricter

src/templates.rs
Since runes functionality is new and complicated, downgrade from `beta` to `alpha` to help set expectations.
=> Downgrade to alpha

Cargo.lock, Cargo.toml, src/index.rs, src/index/rtx.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/index/updater/rune_updater.rs
I implemented this while testing the new redb release, so figured I'd send the PR. Please note that the file format is not backwards compatible, so you'll want to add some upgrade logic if you need it to be backwards compatible.
=> Update redb dependency to 2.0.0

src/runes/edict.rs, src/runes/etching.rs, src/runes/mint.rs, src/runes/runestone.rs
Allow runestone to be deserialized from json.
This would be super-helpful intermediary step until we get a separate library for encoding/decoding payloads.
@casey @raphjaph , I know there are some versions of these that are already deserializable and used by the wallet(eg. wallet/inscribeetch.rs), but if wallet does not expose customization for some fields, they will not be included there. This is needed for protocol convertors, to actually have the exact same structures.
=> Allow runestone to be deserialized from json

crates/test-bitcoincore-rpc/src/api.rs, crates/test-bitcoincore-rpc/src/server.rs, src/inscriptions/media.rs, src/runes.rs, src/runes/runestone.rs, src/subcommand/env.rs, src/wallet.rs, src/wallet/inscribe/batchfile.rs
1. Remove unnecessary parentheses
2. Remove unnecessary path prefix
=> Remove unnecessary code

src/wallet/inscribe/batch.rs
As a sanity check, assert that the runestone deserialized from the etch transaction is correct.
=> Assert etched runestone

src/index/updater/rune_updater.rs, src/runes.rs, src/runes/runestone.rs
Ignore script errors in OP_RETURNS and extracted tapscripts. Both may be invalid, since OP_RETURN scripts are not executed past the first instruction, and our extracted tapscript may not actually be from a taproot output.
=> Ignore errors in invalid scripts

src/wallet/batch/plan.rs, tests/wallet/balance.rs, tests/wallet/batch_command.rs
Set pointer in the etching runestone to ensure if we accidentally spend runes in the input they land back in the wallet.
=> Set pointer in etching runestone

crates/ordinals/src/runestone.rs, src/index/updater/rune_updater.rs, src/subcommand/decode.rs, src/subcommand/wallet/mint.rs, src/subcommand/wallet/send.rs, src/wallet/batch/plan.rs, tests/wallet/batch_command.rs, tests/wallet/send.rs
TIL that script pubkeys aren't required to be valid scripts!
=> Ignore invalid script pubkeys

docs/po/zh.po
- Fixed “order”、“ordinals” and "A through Z" not being properly italicized in《Overview》
- Fixed  "always"  not being properly italicized in 《Digital Artifacts》
- Fixed  Missing closing quotation mark.
=> Fix type in zh.po

src/decimal.rs, src/lib.rs, src/subcommand/wallet/balance.rs, src/subcommand/wallet/batch_command.rs, tests/wallet/balance.rs, tests/wallet/batch_command.rs, tests/wallet/mint.rs
The changes the output for `ord wallet balance`, so it shows the decimal amount instead of just the amount without the divisibiliity included
=> Decimal balance

crates/ordinals/src/runestone.rs, docs/src/runes/specification.md
Partially for documentation purposes, I thought it would be good to include a test which explicitly tests all 256 opcodes for validity.
Opcodes 0 through 78 inclusive are data push opcodes, and can be used in runstones. Opcodes 79 and greater are non pushdata opcodes, and will result in a cenotaph if used in a runestone.
=> Test validity of all opcodes

src/subcommand/env.rs
Problem:
- if `bitcoind` isn't there, the command `ord env` or `cargo run env` fails with an error message - `No such file or directory`
Now it shows the reason:
=> Better error message when bitcoind doesn't start

src/subcommand/wallet/inscribe.rs, src/subcommand/wallet/mint.rs, src/subcommand/wallet/send.rs, tests/wallet/mint.rs
Implements the postage argument for the wallet mint subcommand.
=> Add Postage Argument on Mint Command

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/ordinals/Cargo.toml
- Bump version: 0.17.1 → 0.18.0
=> Release 0.18.0

README.md
Just in case someone is using RedHat/Centos, ord latest tag 0.18.1 can be built on centos 8
=> Add manual for centos

src/index.rs, src/subcommand/server.rs, src/templates/runes.rs, templates/runes.html, tests/json_api.rs
=> Runes pagination

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/ordinals/Cargo.toml
- Bump version: 0.18.1 → 0.18.2
=> Release 0.18.2

src/subcommand/wallet.rs, src/subcommand/wallet/resume.rs
=> Add `dry-run` flag to `resume` command

docs/src/guides/collecting/sparrow-wallet.md
The --wallet flag no longer works, to import wallet with name we need --name flag instead with --from mnemonic flag instead of the current listed: `ord --wallet ord_from_sparrow wallet restore "BIP39 SEED PHRASE"`
=> Update sparrow-wallet.md --name flag update

docs/src/guides/sat-hunting.md
Added the key information about needing to use the sat name in order to transfer a specific uninscribed sat using ord wallet send.  Fixes #3664
=> Update sat-hunting.md with how to transfer specific sats

Cargo.toml, src/subcommand/server.rs
=> Allow longer request body for API

docs/src/inscriptions.md, docs/src/inscriptions/delegate.md, docs/src/inscriptions/recursion.md
Closes #2903
Closes #3208
Adds a few lines to the documentation to make it clear that inscriptions are served from /content/<INSCRIPTION_ID>. Many inscriptions rely on this fact to get their own inscription ID, so it is important that this is properly documented so we know we can rely on this.
Also added clarification regarding the url of inscriptions that have delegates. Happy to remove this if people think it is implicit in the other sentences, but since ord.io is currently making this mistake, I thought it is better to clarify.
Also added an example for how inscriptions can self reference and fetch their own inscription ID. Also happy to remove this, as it isn't directly about the protocol, but rather how to use it. But a lot of people ask how to do this, so having it in the handbook …
=> Add documentation to clarify that inscriptions are served from /content/<INSCRIPTION_ID>

docs/src/guides/sat-hunting.md
apologies - I had a typo in my recent commit; fixed now
=> fix typo on recent commit to sat hunting page

docs/src/guides/explorer.md
the endpoint `/output/<OUTPOINT>` appeared twice in the list.
=> Remove duplicate endpoint from explorer.md

docs/src/guides/sat-hunting.md
Removed disclaimer about the guide being out of date and updated the commands to follow the current version.  Minor spelling and grammar fixes, also.
=> Modernize sat-hunting.md

src/subcommand/wallet/mint.rs
Postage should be allowed to be equal to the dust limit, just not smaller than it.
=> Fix typo in mint.rs

src/settings.rs
=> Make settings public

deploy/ord.service, ord.yaml, src/index.rs, src/index/entry.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/index/updater/rune_updater.rs, src/options.rs, src/re.rs, src/settings.rs, src/subcommand/server.rs, src/templates.rs, src/templates/address.rs, src/templates/status.rs, templates/address.html, templates/status.html, tests/json_api.rs, tests/server.rs, tests/settings.rs
This is a very crude address index, to make this production ready we have to either add an `OUTPOINT_TO_TXOUT` table, or adapt the value cache and fetcher to also get the script pubkey in addition to the output value.
Some more considerations:
- At the moment the table stores the bytes of the script_pubkey as the key. Probably smarter to use the hash of the script_pubkey so that it is of fixed size. Look up would then go Address -> ScriptPukey -> Hash(ScriptPubkey): `SCRIPT_PUBKEY_HASH_TO_OUTPOINT`
- Reuse the `TRANSACTION_ID_TO_TRANSACTION` table.
=> Address index

docs/src/inscriptions/recursion.md, src/api.rs, src/subcommand/server.rs
Added `/r/parents/<INSCRIPTION_ID>` and `/r/parents/<INSCRIPTION_ID>/<PAGE>` endpoints. This should take care of https://github.com/ordinals/ord/issues/3309.
=> Added parents recursive endpoint

docs/src/inscriptions/recursion.md, src/api.rs, src/subcommand/server.rs
Add feerate_percentiles to blockinfo
=> Add feerate_percentiles to blockinfo endpoint

src/subcommand/list.rs, tests/list.rs
fixes #3701 - I've added the `/output/<OUTPOINT>` fields to the `ord list` command into a section called "list'.  I also reordered the fields in the pre-existing "ranges" section to make more logical sense.  There is a small amount of redundancy now with the list.sat_ranges vs ranges.start & end, and list.value vs ranges.size.  I figure that this is acceptable and better than changing the pre-existing ranges section, as some users may already be reliant upon those fields - but let me know if not and if further formatting or changes would be better.
=> Update list.rs to include inscription and rune info

docs/src/inscriptions/recursion.md, src/api.rs, src/subcommand/server.rs, tests/server.rs
Add the delegate ID to the `/inscription/[id]` endpoint. If there is no delegate then the response doesn't include that field.
=> Add delegate value to inscription endpoint

docs/src/inscriptions/recursion.md, src/api.rs, src/subcommand/server.rs
Add `/r/children/:inscription_id/inscriptions` endpoint.
In case #3761 is too heavy, this version avoids doing any `getrawtransaction` calls, at the cost of not returning the following fields: 
* content_type
* content_length
* delegate
* value
On my system this fetches the first 100 pizza ninja children in about 50 ms, compared to 7250 ms using the previous PR (#3761). That's about 150 times faster. Turns out fetching the raw transactions is kind of slow.
=> Fetch child inscriptions without using `getrawtransaction`

src/subcommand/env.rs
fixes #3460;  this panic was still occurring in 0.18.5 on my Windows machine.  I was able to test this change there and it fixes the issue by allowing for shutdown without panic.
=> fix panic in ord env shutdown

src/blocktime.rs, src/index.rs, src/index/entry.rs, src/inscriptions/inscription.rs, src/inscriptions/media.rs
This is exposing the main index api to apps importing `ord`.
In the context of apps doing that to listen to ordinal/rune events, it enables more information be retrieved once an event is received. For example, even though the `InscriptionCreated` doesn't come with the inscription's content, we can easily get it using `index.get_inscription_by_id(inscription_id)`.
=> Make Index public

src/lib.rs
This enables apps to gracefully shutdown the `index.update()`
=> Create public shutdown function

Cargo.lock, Cargo.toml, src/arguments.rs, src/error.rs, src/index.rs, src/lib.rs, tests/settings.rs, tests/wallet/sats.rs
This migrates a couple error sites over to `snafu`, a library for typed errors. `snafu` has a nice system of context selectors, which makes it easy to attach context to an underlying error.
This only migrates two error sites, and leaves migration of other error sites to future PRs.
@raphjaph @cryptoni9n
=> Add typed errors with `snafu`

README.md
It was mentioned here by @casey https://github.com/ordinals/ord/issues/1471#issuecomment-1421615258 that this small tips in README could help a lot of folks.
=> Add debugging tips to show full Rust backtrace

src/subcommand/wallet.rs, src/subcommand/wallet/label.rs, src/subcommand/wallet/outputs.rs, src/subcommand/wallet/sats.rs, src/wallet.rs, tests/wallet/outputs.rs
partially addresses #3792 by adding the sat ranges to the `ord wallet output` command.  My feeling is that the sat ranges are information about the outputs, so this is a good place for this information.  
Next, I'll add the --all flag  so that `ord wallet sats --all` will return all sat ranges, and `ord wallet sats` without a flag will continue to only show rare sats (as it does today).  
The description for the command says `List wallet satoshis` - but what do we want this output to look like?  Should it simply be a list of sat ranges with no reference to the outputs, or anything else?  Would something like the mock-up below be acceptable? or do we want to display more info?
> `ord wallet sats --all`
[1111111111111111-1111111111111112, 1111111111111113-1111111111111114, …
=> Add sat ranges to output

src/subcommand/wallet/sats.rs, tests/wallet/sats.rs
further addressing #3792 
return all sat ranges in wallet, in addition to
the rare sats the command normally returns.
=> added the --all flag on `ord wallet sats`

src/index.rs, src/subcommand/server.rs, src/templates/address.rs, templates/address.html, tests/server.rs
Hi! First ever public pull request 🙏  Please feedback is welcome
Referencing issue #3809 to add more information to address page. I also refactored the tests on templates/address.rs so that different categories of address information are tested separately. 
Unfortunately, I'm not able to get the integration at tests/server.rs to work; it seems to be that rune commands are not compatible with the mockcore::spawn() handle, hence it is necessary to enforce the transaction on regtest; however I get a 404 error when requesting pages with a regtest address format; so the test currently always fails.
=> Display rune balances in address page

docs/po/pt.po
Runes section was translated and updated to Portuguese.
=> Update Portuguese Translation pt.po

templates/address.html
partially addresses #3846 by fixing the linking/display for runes that have the default currency symbol.  runes with default currency symbol will now be linked and show the symbol on the /address page.
=> fix rune links for runes with default currency symbol on /address page

src/subcommand/wallet/outputs.rs, tests/wallet/outputs.rs
#3817 introduced #3865 where `ord wallet outputs` would display the sat_ranges: field with an empty set for each output if it was run without the `--ranges` flag.  This fixes it so that the sat_ranges: field only appears when the command is run with the `--ranges` flag.
=> suppress-sat_ranges-by-default

docs/src/runes/specification.md
Add missing info for pointer description:
`If the pointer is greater than the amount of output, runestone is a cenotaph.`
=> Update pointer specification

src/subcommand/server.rs, src/subcommand/server/server_config.rs
pull request for issue:  https://github.com/ordinals/ord/issues/3850
=> add headers for cross-origin-isolated to enable SharedArrayBuffer

src/subcommand.rs, src/subcommand/wallets.rs
This basically just wraps `bitcoin-cli listwalletdir`. In order to filter by if it is an ordinals wallet we would have to load all wallets and then check the descriptor. This can take a while so I haven't implemented it here. I think we could add `--ordinals-only` that does this this.
=> List all Bitcoin Core wallets

src/subcommand/server.rs, src/subcommand/server/server_config.rs
To avoid setting `Cross-Origin-Resource-Policy: same-site`, which is too permissive.
=> Revert "Serve responses with cross origin isolation headers"

Cargo.lock, Cargo.toml, ord.yaml, src/index.rs, src/index/entry.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/index/utxo_entry.rs, src/lib.rs, src/options.rs, src/settings.rs, src/subcommand/server.rs, tests/info.rs, tests/settings.rs
Replace the OUTPOINT_TO_TXOUT, OUTPOINT_TO_SAT_RANGES, and SATPOINT_TO_SEQUENCE_NUMBER tables with a new OUTPOINT_TO_UTXO_ENTRY table.  This saves space by avoiding redundant key storage, and makes updates quicker since we can write all of an outpoint's data at once.
It also simplifies caching.  We used to have utxo_cache for OUTPOINT_TO_TXOUT and range_cache for OUTPOINT_TO_SAT_RANGES, while SATPOINT_TO_SEQUENCE_NUMBER was uncached; now, there's a single unified utxo_cache which covers all three.  Additionally, since SCRIPT_PUBKEY_TO_OUTPOINT and SEQUENCE_NUMBER_TO_SATPOINT are storing data which is already included in the cache (just with the keys and values swapped), we get to cache those tables too for free.
The combined effect is that an index with --index-sats and --index-addresses …
=> Unified OUTPOINT_TO_UTXO_ENTRY table

ord.yaml, src/index.rs, src/index/updater.rs, src/options.rs, src/settings.rs, tests/json_api.rs, tests/settings.rs
When using --index-sats or --index-addresses, we need to index all blocks, but --index-inscriptions only needs blocks starting from 767430, and --index-runes can start at 840000.  The existing code for this is tricky and also wrong -- it incorrectly skips early blocks when using --index-addresses but not --index-sats, and it unnecessarily processes blocks from 767430 to 840000 when using --index-runes but not --index-inscriptions.
Replace the old code with a single, correct calculation of which block to start at.  This speeds up building a runes-only index by about 4x.
=> Start indexing at the appropriate block

Cargo.lock, Cargo.toml, src/lib.rs, src/subcommand/wallet.rs, src/subcommand/wallet/dump.rs, src/wallet.rs, src/wallet/batch/plan.rs, src/wallet/wallet_constructor.rs, tests/lib.rs
We need to upgrade `rust-bitcoin`. In order to do that we need to get rid of the dependency on our fork of `bitcoincore_rpc`. This works because most of the reason we forked it was for the now separate `mockcore` crate.
=> Remove dependency on `ord-bitcoincore-rpc` crate

crates/ordinals/src/sat.rs, src/index/updater.rs, src/index/updater/inscription_updater.rs, src/lib.rs
Keep our arrays of sat ranges in the low-level `[u8; 11]` format, rather than converting them to `(u64, u64)` and back.  Also, don't mutate the input sat ranges in `index_transaction_sats()`; this avoids the need for a copy in `index_utxo_entries()` and also makes that code simpler.
Add a fast path for `Sat::common()`, which avoids a divide and some branch mispredictions.
These changes save almost 2.5 hours of CPU time.  The overall speedup is less, though, because indexing now runs fast enough that bitcoind often can't keep up -- we spend a significant amount of time just waiting for it to send us blocks.
=> More efficient sat-range handling

src/subcommand/wallet/inscribe.rs
@raphjaph `Option<T>` actually has an `as_slice` method which returns a zero or one length slice depending on whether the `Option` is `Some`.
=> Use `as_slice` instead of convert to vec

src/wallet/batch/file.rs
@raphjpah Non-final nouns in noun compounds are always singular.
=> Rename parents_values -> parent_values

CHANGELOG.md, Cargo.lock, Cargo.toml, justfile, src/index.rs, src/index/utxo_entry.rs
- Bump version: 0.20.1 → 0.21.0
=> Release 0.21.0

src/subcommand/server.rs, src/templates/rune.rs, templates/rune.html, tests/lib.rs
We've been displaying mint progress as the completely inexplicable `supply / max_supply`. Change it to number of mints / maximum number of mints.
=> Change mint progress to `mints / terms.cap`

src/api.rs, src/index.rs, src/subcommand/server.rs, src/templates/inscription.rs, templates/inscription.html, tests/json_api.rs, tests/wallet/inscribe.rs
Add a child totalizer to the inscription page.
=> Show total child count

src/subcommand/server.rs, src/templates/iframe.rs, templates/preview-image.html
In #3947, we allowed scrolling in iframes. I recently visited ordinals.com on windows, and there were hideous scrollbars on nearly every inscription.
This isn't a windows-specific issue, i.e., the scrollbars are there on macOS, they just look worse on Windows, which is why we didn't notice.
This PR does a couple things:
- Add `float: left` to images in the image preview. This, for some reason, makes the images the correct size, so they don't overflow, due to some mysterious CSS behavior that I don't fully understand.
- Add back `scrolling=no` to inscription thumbnails. This prevents scrollbars for appearing everywhere except the actual /inscription page, which I think is better. There's no reason to allow scrolling a thumbnail, especially if the user can just click it to scroll.
I'm still …
=> Hide image preview and thumbnail scrollbars

crates/mockcore/src/lib.rs, crates/mockcore/src/server.rs, crates/mockcore/src/state.rs, src/subcommand/wallet/create.rs, src/subcommand/wallet/restore.rs, src/wallet.rs, tests/wallet/restore.rs
=> Rescan wallet when restoring from mnemonic 

crates/ordinals/src/lib.rs, crates/ordinals/src/runestone.rs
I believe the `MAX_SCRIPT_ELEMENT_SIZE` limit is only checked when outputs are spent. Since runestones begin with an `OP_RETURN`, they can never be spent, so we do not need to chunk the payload.
It's unfortunate that I'm only realizing this now, since if I had known it earlier, we could have required the payload to be a single data push, since without the `MAX_SCRIPT_ELEMENT_SIZE` limit, there's no reason to accept multiple data pushes in the payload.
This is marked as a draft PR, because although I think it's correct, I want to actually test it against Bitcoin Core to confirm before merging.
=> Do not split runestone payload into MAX_SCRIPT_ELEMENT_SIZE pushes

src/subcommand/server.rs, src/templates.rs, src/templates/block.rs, src/templates/blocks.rs, src/templates/inscription.rs, src/templates/output.rs, src/templates/sat.rs, static/index.css, static/index.js, templates/block.html, templates/blocks.html, templates/inscription.html, templates/output.html, templates/page.html, templates/rune-balances.html, templates/sat.html, templates/status.html, templates/transaction.html, tests/server.rs, tests/wallet/batch_command.rs, tests/wallet/send.rs
This PR uses JavaScript to collapse hashes, outpoints, satpoints, addresses, and inscription IDs.
Any node which has exactly one child node which is a text mode that matches a regex matching the above is eligible to be collapsed. A `data-original` attribute is added with the original text, and on resize, the size of the element is measured, and if smaller than the size of the text content, the text content is abridged in the middle with `…`.
Since the text content is now changed, we need to fix clipboard copying, so that users can copy the original unabridged text. This is accomplished by intersecting clipboard copy events, and, if they target a collapsible node, replacing the copied text with the original text. One failing of this approach is that if you copy multiple nodes, the target …
=> Collapse long strings in HTML

src/subcommand/server.rs, src/templates/address.rs, src/templates/block.rs, src/templates/blocks.rs, src/templates/input.rs, src/templates/inscription.rs, src/templates/output.rs, src/templates/rune.rs, src/templates/sat.rs, src/templates/transaction.rs, static/index.css, static/index.js, templates/address.html, templates/block.html, templates/blocks.html, templates/input.html, templates/inscription.html, templates/output.html, templates/rune-balances.html, templates/rune.html, templates/sat.html, templates/status.html, templates/transaction.html, tests/lib.rs, tests/server.rs, tests/wallet/batch_command.rs, tests/wallet/send.rs
Instead of identifying collapsible with `class=collapse`, instead of with a regular expression.
This is faster, simpler, and less error prone. Going forward, any elements which should be collapsable should get this class. Things like addresses, any kind of hash, outpoints, and satpoints, should be collapsable.
=> Identify collapsible nodes with class=collapse

Cargo.toml, src/subcommand/server.rs
This PR adds an `assert_html` test method which takes a path and a value implementing `PageContent`, and asserts that the page returned from the server is the same as that from rendering the value as an HTML template.
I think this is a dramatic improvement over our HTML / regex-based tests, which have terrible diffs and are super verbose, and basically force the test to recreate all the formatting of templates.
I only converted three instances of the old test type to use `assert_html`. I think going forward, we should change to `assert_html` whenever a test breaks.
=> Add assert_html function

src/subcommand/wallet/restore.rs, src/wallet.rs, tests/wallet/restore.rs
=> Add a timestamp to restore

crates/ordinals/Cargo.toml
I needed to pin `bitcoin` to 0.32.3 in `ordinals` crate to publish it.
=> Pin `bitcoin` to 0.32.3 in `ordinals` crate

src/subcommand/server.rs, src/templates/output.rs, templates/output.html
Sat ranges are no longer intervals, and instead link to the first and last sat in the range. However, the last sat is off by one. Fix that.
=> Fix off-by-one-error in sat range template

src/inscriptions/inscription.rs
I need this method when build a custom wallet. Thanks.
=> Make build script public

bin/replicate, bin/swap, justfile
`just replicate` copies indices from `charlie` to `alpha` and `bravo`
`just swap HOST` swaps in the new index on the given host.
=> Add replicate and swap recipes

crates/ordinals/src/rune.rs
See `Rune::unlock_height`. This works but makes me nervous. I noticed that my height calculation was one too high whenever we were 0/4, 1/4, 2/4, or 3/4ths of the way through an interval of runes with a given length. So I just fudged it and subtracted one in those cases.
I've exhaustively tested lengths 1 through 7, and they're all correct. (Checked by cross checking with asserts that the result of `Rune::unlock_height` matches `Rune::minimum_at_height`.) However, I'm worried that this pattern is actually the result of some deep number theory harmonic integer sequence or something, and is somehow wrong for larger intervals.
=> Add function to calculate rune unlock height

src/templates/inscription.rs, templates/inscription.html, tests/server.rs
Nobody uses this and it confuses people. This PR just doesn't display the address on the frontend, all other teleburn logic remains.
=> Do not display teleburn address

src/subcommand/wallet/burn.rs, src/subcommand/wallet/send.rs, tests/wallet/send.rs
The help text is definitely an improvement. I also think that changing the argument name from `outgoing` to `asset` is also an improvement. I'm not sure about changing `outgoing` to `asset` in the output. I think it's better, but it breaks any commands relying on it.
=> Improve `ord wallet send` help message

crates/mockcore/src/api.rs, crates/mockcore/src/lib.rs, crates/mockcore/src/server.rs, src/subcommand/wallet/burn.rs, src/subcommand/wallet/send.rs, src/subcommand/wallet/split.rs, src/wallet.rs, tests/wallet/burn.rs, tests/wallet/inscribe.rs
Tested locally on regtest. Also bumps minimum bitcoin core version to 25, so we can pad to 65 bytes, instead of 82 bytes.
See this PR:
https://bitcoincore.reviews/26265
=> Set `maxburnamount` when burning

src/subcommand/wallet/burn.rs, tests/wallet/burn.rs
Resolves #3977 
Tbh not sure if it's actually that simple. Tested with [this inscription](https://ordinals.com/inscription/fb2de94a4b1c30dbf9c228dec2971ae1bc88ffb3479ae59ecb981f1f65add1eci0). And this was the [burn tx](https://mempool.space/tx/97ad0dae72ab33fa0e64cc573d3b54d19a282c2e1af6bb0ac326f41d6c67c503).
=> Only burn one sat

src/arguments.rs
The main difference is that headings are in yellow, which sets them off a bit.
<details>
</details>
=> Style help text

CHANGELOG.md, Cargo.lock, Cargo.toml
- Bump version: 0.21.3 → 0.22.0
=> Release 0.22.0

Cargo.lock, Cargo.toml, src/index.rs, src/wallet.rs
This enables redb's new quick-repair mode so you can try it out.  It's using redb master, since this version hasn't been released yet.
Recovery after a crash always means rolling back to the last complete commit; if that commit was made with quick-repair enabled, then recovery will be instant.  So to get the new behavior, you'll need to let it make one successful commit with the new code before you start making it crash.  After that, no matter what you do, you should never have to wait for repair again.  You can tell it's working because it won't print the "Index file needs recovery" message, even after a crash; it'll just look like a normal clean startup.
Quick-repair mode needs to save the database allocator state with each commit, which costs about 200 ms per commit for a 190 GB …
=> Enable redb's new quick-repair mode

src/wallet.rs, src/wallet/wallet_constructor.rs
Addresses #4091 and #4111.
@gmart7t2 This catches a couple of errors that usually occur when the wallet takes a long time to load. It should now wait until a wallet or descriptor is finished loading before proceeding. 
Do you know by chance what the Bitcoin Core error code or message is if a descriptor for a wallet is still loading?
=> Wait for wallet to load

src/subcommand/wallet/burn.rs, src/subcommand/wallet/send.rs, src/wallet.rs, tests/lib.rs, tests/wallet/burn.rs
Closes #3640
Tested on mainnet:
https://mempool.space/tx/80516dbf06b3f9052ae0fb05b2e15db5fabbe5226e02019529571f00620c9740
https://ordinals.com/rune/RUNESREFRIGERATOR
=> Enable rune burning in wallet

static/preview-video.js, templates/preview-video.html
This PR modifies inscription video previews so controls (play, pause, etc) are only visible after clicking the preview.
Since thumbnail iframes are wrapped with an `<a>` tag, the `<a>` tag will intecept any clicks, so it entirely disables video controls on thumbnails, which I think is correct.
On `/inscription` the preview iframe isn't wrapped with an `<a>`, so you can enable controls by clicking on it.
I think this is nice, since otherwise video inscriptions load with visible controls, which is not very nice looking.
=> Show video controls on click

static/index.css, templates/blocks.html
Show overflow on `<ol>` in /blocks list. The only thing that overflows is the block number on each `<li>`. I'm not sure why we hid it in the first place, but it looks pretty bad.
I also simplified the template slightly by calculating the height up front for each block, and indented the rust code to match the indentation level it would have in actual code.
=> Show overflow on <ol> in /blocks list

docs/src/overview.md
It might be worth @gmart7t2 double-checking these figures before they're committed. Original discussion is here: https://github.com/ordinals/ord/issues/3587 Thanks
=> Correct total sat supply figures & update current sat supply figures

crates/ordinals/src/rarity.rs
I wanted to double check these before merging #4152, so I I added a method to `Rarity` which returns the supply, along with a test to ensure that the figures are correct.
=> Add method returning rare sat supply

docs/src/guides/wallet.md
#4106 updated the required version of Bitcoin Core to 25 - this updates the documentation.
thanks to @so7ow for pointing this out
=> update minimum required bitcoin core version to v25

src/subcommand/env.rs
We were very aggressive with killing the process. Not allowing Bitcoinn Core time to process the `kill` command, which lead it to bork it's database. This now waits 5 seconds, giving it enough time to exit.
=> `ord env` less aggressive exit

src/inscriptions/media.rs
Allows inscribing torrent files with `ord`. Doesn't add any preview functionality, although that could be added later.
=> Use `application/x-bittorrent` media type for `.torrent` files

src/inscriptions/media.rs
https://ordinals.com/inscription/8088a6bc04b249f252fd440a7b4436392e6bafb8b42efca73b0f235a13d52808i0
=> Add .opus to audio types

src/templates/inscriptions_block.rs
=> Don't error when listing inscriptions in a block without inscriptions

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/ordinals/Cargo.toml, justfile, src/satscard.rs
- Bump version: 0.22.1 → 0.22.2
- Bump `ordinals` version: 0.0.14 → 0.0.15
=> Release 0.22.2

src/subcommand/server.rs, src/subcommand/server/r.rs
This avoids the overhead of having to implement the NotFound proxy for each endpoint individually.
=> Use middleware for proxied endpoint

Cargo.toml
Reorg just happened today and I have a version of ord 22.1 running redb 2.3.0 that is still working to recover(and probably will take 1-2 hours) and the one with redb 2.4.0 recovered in 1 second.
https://github.com/cberner/redb/releases/tag/v2.4.0
https://github.com/ordinals/ord/issues/4207 @raphjaph
=> Upgrade redb to 2.4.0 to improve reorg performance

src/wallet/batch/file.rs
Noticed that the pointer gets bumped by the postage amount for every inscription even when in `SameSat` mode. Added a small fix to only bump the pointer when in other modes.
This doesn't change which sat inscriptions are attached to because they all overflow back to a pointer of 0 anyway. You do save some space on unnecessary pointers though.
=> Don't unnecessarily bump pointer by postage for SameSat mode

.github/workflows/ci.yaml
I think this is slightly clearer, since it moves the `LANGUAGES` variable to where it's actually used.
=> Move CI LANGUAGES variable into job that uses it

src/inscriptions.rs, src/inscriptions/envelope.rs, src/lib.rs
Fix #4246, the PR allows people to access ParsedEnvelope::from_transaction for parsing inscriptions from their Rust code.
=> Make ParsedEnvelope and Envelope public

src/inscriptions/media.rs
When making inscriptions, we prefer to use the most specific content type possible, including media type parameters. However, when deciding to use which preview to use, we should accept media types without parameters.
Fixes #4285.
=> Recognize inscriptions with content type `audio/ogg` as audio

src/subcommand/server.rs, src/subcommand/server/r.rs, src/templates/preview.rs, templates/preview-audio.html, templates/preview-code.html, templates/preview-font.html, templates/preview-iframe.html, templates/preview-image.html, templates/preview-markdown.html, templates/preview-model.html, templates/preview-pdf.html, templates/preview-text.html, templates/preview-video.html
Add better titles to preview pages (per https://github.com/ordinals/ord/issues/4264)
In this solution, `inscription_number` is fetched from the index entry where necessary, and passed to the preview structs and templates, to be used as part of the HTML title tags, respectively. Note also `inscription_number` is added to the `r::content_response` function signature, to be able to be passed to `PreviewIframeHtml`, and explicitly set to 0 in tests.
=> Better preview titles

static/index.css
Render borders around thumbnails. This makes the main page a lot nicer when inscriptions are slow to load. I also made the borders lighten up a little bit on hover, which helps to indicate that they're clickable.
You can't see the mouse, but the second screenshot shows what it looks like on hover.
<details>
<summary>Screenshots</summary>
</details>
=> Render borders around thumbnails

src/blocktime.rs, src/subcommand/server.rs, src/templates/rune_not_found.rs, templates/rune-not-found.html
We reuse the `Blocktime` struct which already does this, instead of only using the timestamp.
=> Don't display `(expected)` when rune has already unlocked

src/inscriptions/media.rs
JPEG XL is [not widely supported](https://caniuse.com/?search=jpegxl).
However, you can take advantage of the format to create extremely small but visually compelling images, which is perfect for inscribing. [example](https://jxl-art.surma.technology/).
So, we could consider adding the `jxl` extension and allow `ord` to inscribe `jxl` without issue. This would be a different policy than usual, since if people don't know that JPEG XL isn't widely available, they might inscribe it and be disappointed when it only appears correctly in Safari.
=> Allow inscribing JPEG XL

crates/ordinals/src/sat_point.rs, src/index/updater/inscription_updater.rs
This PR fixes two typos:
1. In sat_point.rs: Changed "and output" to "an output" in the documentation comment
2. In inscription_updater.rs: Fixed spelling of "rules" in the comment
These changes improve code documentation clarity without affecting functionality.
=> Fix typos in documentation and comments

src/templates/inscription.rs, templates/inscription.html
The `<details>` item on `/inscription` has been bothering me. We initially intended to move more things into it, so it's just kind of pointless right now, since it takes up the same amount of space as the only item it contains.
I think we should remove `<details>` for now, and pull the `ethereum teleburn address` to the top level. If, later, we have multiple items that we really have a strong rationale for moving into `<details>` we can re-introduce it.
=> Move ethereum teleburn address out of details

src/settings.rs
The bitcoin RPC client would sometimes fail to connect with a "Resource temporarily unavailable" error.
Retrying the connection on this error solved the issue for me.
=> Rpc client retries when "Resource temporarily unavailable"

Dockerfile
Bumps the Dockerfile's builder image from `rust:1.79.0-bookworm` to `rust:1.81.0-bookworm`.
The project no longer builds at 1.79 and so this PR bumps it to the minimum `rustc` version at which the project builds again.
I am not very well-versed in rust dependency chains or module resolution, but `Cargo.toml` currently sets `rust-version = "1.80.0"` which appears to be too low as well. I'm leaving it untouched for now.
=> Update Dockerfile rust image

Cargo.toml, Dockerfile, tests/wallet/inscribe.rs
rust version 1.85.0 minimum is required for this build. Upgrading to latest stable release (1.87.0). Fixing the error below
```
3.806 error: failed to parse manifest at `/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-2.5.0/Cargo.toml`
3.806 
3.806 Caused by:
3.806   feature `edition2024` is required
3.806 
3.806   The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
3.806   Consider trying a newer version of Cargo (this may require the nightly release).
3.806   See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```
=> Update minimum Rust version to 1.85.0

docs/src/guides/api.md
Corrected a typo in the API documentation route path:
- TRANSCATION_ID → TRANSACTION_ID
This fix ensures accurate reference to the /decode/<TRANSACTION_ID> endpoint and prevents confusion for users interacting with the API.
=> Fix typo in API route example
